#ifndef __GPIO_SETTING_H
#define __GPIO_SETTING_H

#include <asm/arch/gpio.h>
#include <asm/arch/cpu.h>

#define PDN_MASK(x)		(0x3 << ((x) << 1))

#define CON_INPUT(x)		(0x0 << ((x) << 2))
#define CON_OUTPUT(x)		(0x1 << ((x) << 2))
#define CON_IRQ(x)		(0xf << ((x) << 2))

#define DAT_SET(x)		(0x1 << (x))
#define DAT_CLEAR(x)		(0x0 << (x))

#define OUTPUT0(x)		(0x0 << ((x) << 1))
#define OUTPUT1(x)		(0x1 << ((x) << 1))
#define INPUT(x)		(0x2 << ((x) << 1))
#define KEEP_STATE(x)		(0x3 << ((x) << 1))

#define PULL_DIS(x)		(0x0 << ((x) << 1))
#define PULL_DOWN(x)		(0x1 << ((x) << 1))
#define PULL_UP(x)		(0x2 << ((x) << 1))

#define PREVIOUS(x)		(0x3 << ((x) << 1))

#define HWSUGGEST
#ifdef HWSUGGEST
#define PDNCON_NC(x)		INPUT(x)
#define PDNPUD_NC(x)		PULL_DOWN(x)
#else
#define PDNCON_NC(x)		OUTPUT0(x)
#define PDNPUD_NC(x)		PULL_DIS(x)
#endif

/* #define OPTMIZED_SLEEP_CURRENT_BCM4329 */

struct gpio_powermode {
	unsigned int	conpdn;
	unsigned int	pudpdn;
};

struct gpio_external {
	unsigned int	con;
	unsigned int	dat;
	unsigned int	pud;
};

/* In mirror mode, it sets "I(PD/PU)" according to the
 * output at the u-boot time. */
struct s5pc1xx_gpio_item {
	struct s5p_gpio_bank *bank;
	unsigned int number;
};

static struct s5pc1xx_gpio_item aquila_mirror_powerdown_mode[] = {
};

static struct s5pc1xx_gpio_item kessler_mirror_powerdown_mode[] = {
	{ .bank = &((struct s5pc110_gpio *)S5PC110_GPIO_BASE)->j0, .number = 2},
	{ .bank = &((struct s5pc110_gpio *)S5PC110_GPIO_BASE)->j0, .number = 3},
	{ .bank = &((struct s5pc110_gpio *)S5PC110_GPIO_BASE)->j0, .number = 4},
	{ .bank = &((struct s5pc110_gpio *)S5PC110_GPIO_BASE)->j0, .number = 7},
};

#undef __GPIO

static struct gpio_powermode aquila_powerdown_modes[] = {
	{	/* S5PC110_GPIO_A0_OFFSET */
		INPUT(0) | OUTPUT0(1) | INPUT(2) | OUTPUT0(3) |
		INPUT(4) | OUTPUT0(5) | INPUT(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_A1_OFFSET */
		INPUT(0) | OUTPUT0(1) | INPUT(2) | INPUT(3),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3),
	}, {	/* S5PC110_GPIO_B_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		INPUT(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_C0_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | INPUT(3) |
		OUTPUT0(4),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110_GPIO_C1_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | INPUT(3) |
		OUTPUT0(4),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110_GPIO_D0_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3),
	}, {	/* S5PC110_GPIO_D1_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | INPUT(3) |
		INPUT(4) | INPUT(5),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5),
	}, {	/* S5PC110_GPIO_E0_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | INPUT(3) |
		INPUT(4) | INPUT(5) | INPUT(6) | INPUT(7),
		PULL_DOWN(0) | PULL_DOWN(1) | PULL_DOWN(2) | PULL_DOWN(3) |
		PULL_DOWN(4) | PULL_DOWN(5) | PULL_DOWN(6) | PULL_DOWN(7),
	}, {	/* S5PC110_GPIO_E1_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | OUTPUT0(3) |
		OUTPUT0(4),
		PULL_DOWN(0) | PULL_DOWN(1) | PULL_DOWN(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110_GPIO_F0_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_F1_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_F2_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_F3_OFFSET */
		/*
		 * GPF3[4]: CODEC_LDO_EN can be enabled at suspend
		 */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5),
	}, {	/* S5PC110_GPIO_G0_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110_GPIO_G1_OFFSET */

		/*
		 * Chip Status:			Off	On	
		 * GPG1[2]: WLAN_nRST		low	high (need to verify)
		 */
#ifdef OPTMIZED_SLEEP_CURRENT_BCM4329
		OUTPUT0(0) | INPUT(1) | OUTPUT0(2) | INPUT(3) |
#else
		OUTPUT0(0) | INPUT(1) | KEEP_STATE(2) | INPUT(3) |
#endif
		INPUT(4) | INPUT(5) | INPUT(6),
		PULL_DIS(0) | PULL_UP(1) | PULL_DIS(2) | PULL_UP(3) |
		PULL_UP(4) | PULL_UP(5) | PULL_UP(6),
	}, {	/* S5PC110_GPIO_G2_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110_GPIO_G3_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT1(2) | INPUT(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110_GPIO_I_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | INPUT(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110_GPIO_J0_OFFSET */
		INPUT(0) | OUTPUT0(1) | INPUT(2) | INPUT(3) |
		INPUT(4) | INPUT(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DOWN(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_J1_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_J2_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		INPUT(4) | OUTPUT0(5) | INPUT(6) | INPUT(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DOWN(6) | PULL_DOWN(7),
	}, {	/* S5PC110_GPIO_J3_OFFSET */
		INPUT(0) | INPUT(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT1(4) | OUTPUT0(5) | INPUT(6) | INPUT(7),
		PULL_DOWN(0) | PULL_DOWN(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_GPIO_J4_OFFSET */
		INPUT(0) | OUTPUT0(1) | OUTPUT0(2) | INPUT(3) |
		OUTPUT0(4),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110_MP0_1_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT1(2) | OUTPUT0(3) |
		OUTPUT1(4) | OUTPUT0(5) | OUTPUT1(6) | OUTPUT1(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_MP0_2_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | INPUT(2) | OUTPUT0(3),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3),
	}, {	/* S5PC110_MP0_3_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT1(2) | OUTPUT0(3) |
		INPUT(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_MP0_4_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | INPUT(3) |
		INPUT(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DOWN(3) |
		PULL_DOWN(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_MP0_5_OFFSET */
		INPUT(0) | OUTPUT0(1) | INPUT(2) | INPUT(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DOWN(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_MP0_6_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110_MP0_7_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	},
};

static struct gpio_external aquila_external_powerdown_modes[] = {
	{	/* S5PC110_GPIO_H0_OFFSET */
		CON_OUTPUT(0) | CON_INPUT(1) | CON_OUTPUT(2) | CON_OUTPUT(3) |
		CON_OUTPUT(4) | CON_OUTPUT(5) | CON_INPUT(6) | CON_IRQ(7),
		DAT_SET(0) | DAT_CLEAR(2) | DAT_CLEAR(3) |
		DAT_CLEAR(4) | DAT_CLEAR(5),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5),
	}, {	/* S5PC110_GPIO_H1_OFFSET */
		CON_INPUT(0) | CON_INPUT(1) | CON_OUTPUT(2) | CON_IRQ(3) |
		CON_INPUT(4) | CON_INPUT(5) | CON_OUTPUT(6) | CON_INPUT(7),
		DAT_SET(0),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DOWN(4),
	}, {	/* S5PC110_GPIO_H2_OFFSET */
		CON_OUTPUT(0) | CON_OUTPUT(1) | CON_OUTPUT(2) | CON_OUTPUT(3) |
		CON_IRQ(4) | CON_IRQ(5) | CON_IRQ(6) | CON_IRQ(7),
		DAT_CLEAR(0) | DAT_CLEAR(1) | DAT_CLEAR(2) | DAT_CLEAR(3),
		0,
	}, {	/* S5PC110_GPIO_H3_OFFSET */
		CON_IRQ(0) | CON_IRQ(1) | CON_IRQ(2) | CON_OUTPUT(3) |
		CON_IRQ(4) | CON_INPUT(5) | CON_IRQ(6) | CON_OUTPUT(7),
		DAT_CLEAR(3) | DAT_CLEAR(7),
		0,
	},
};

static struct gpio_powermode kessler_powerdown_modes[] = {
	{	/* S5PC110(ARIES)_GPIO_A0_OFFSET */
		INPUT(0) | OUTPUT0(1) | INPUT(2) | OUTPUT0(3) |
		INPUT(4) | OUTPUT0(5) | INPUT(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_A1_OFFSET */
		INPUT(0) | OUTPUT0(1) | INPUT(2) | INPUT(3),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3),
	}, {	/* S5PC110(ARIES)_GPIO_B_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		INPUT(4) | OUTPUT0(5) | PDNCON_NC(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PDNPUD_NC(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_C0_OFFSET */
		OUTPUT0(0) | PDNCON_NC(1) | OUTPUT0(2) | INPUT(3) |
		OUTPUT0(4),
		PULL_DIS(0) | PDNPUD_NC(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110(ARIES)_GPIO_C1_OFFSET */
		OUTPUT0(0) | PDNCON_NC(1) | OUTPUT0(2) | INPUT(3) |
		OUTPUT0(4),
		PULL_DIS(0) | PDNPUD_NC(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110(ARIES)_GPIO_D0_OFFSET */
		PDNCON_NC(0) | OUTPUT0(1) | PDNCON_NC(2) | PDNCON_NC(3),
		PDNPUD_NC(0) | PULL_DIS(1) | PDNPUD_NC(2) | PDNPUD_NC(3),
	}, {	/* S5PC110(ARIES)_GPIO_D1_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | INPUT(3) |
		INPUT(4) | INPUT(5),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5),
	}, {	/* S5PC110(ARIES)_GPIO_E0_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | INPUT(3) |
		INPUT(4) | INPUT(5) | INPUT(6) | INPUT(7),
		PULL_DOWN(0) | PULL_DOWN(1) | PULL_DOWN(2) | PULL_DOWN(3) |
		PULL_DOWN(4) | PULL_DOWN(5) | PULL_DOWN(6) | PULL_DOWN(7),
	}, {	/* S5PC110(ARIES)_GPIO_E1_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | OUTPUT0(3) |
		PDNCON_NC(4),
		PULL_DOWN(0) | PULL_DOWN(1) | PULL_DOWN(2) | PULL_DIS(3) |
		PDNPUD_NC(4),
	}, {	/* S5PC110(ARIES)_GPIO_F0_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_F1_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_F2_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_F3_OFFSET */
		/*
		 * GPF3[4]: CODEC_LDO_EN can be enabled at suspend
		 */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		INPUT(4) | PDNCON_NC(5),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DOWN(4) | PDNPUD_NC(5),
	}, {	/* S5PC110(ARIES)_GPIO_G0_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | INPUT(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110(ARIES)_GPIO_G1_OFFSET */
#ifdef OPTMIZED_SLEEP_CURRENT_BCM4329
		OUTPUT0(0) | OUTPUT1(1) | OUTPUT0(2) | OUTPUT1(3) |
		OUTPUT1(4) | OUTPUT1(5) | OUTPUT1(6),
#else
		OUTPUT0(0) | OUTPUT1(1) | KEEP_STATE(2) | OUTPUT1(3) |
		OUTPUT1(4) | OUTPUT1(5) | OUTPUT1(6),
#endif
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110(ARIES)_GPIO_G2_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | INPUT(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110(ARIES)_GPIO_G3_OFFSET */
		OUTPUT1(0) | OUTPUT0(1) | PDNCON_NC(2) | INPUT(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PDNPUD_NC(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110(ARIES)_GPIO_I_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		OUTPUT0(4) | OUTPUT0(5) | OUTPUT0(6),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6),
	}, {	/* S5PC110(ARIES)_GPIO_J0_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | INPUT(3) |
		INPUT(4) | INPUT(5) | OUTPUT0(6) | INPUT(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_J1_OFFSET */
		OUTPUT1(0) | OUTPUT0(1) | OUTPUT0(2) | INPUT(3) |
		INPUT(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DOWN(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_J2_OFFSET */
		OUTPUT0(0) | OUTPUT0(1) | OUTPUT0(2) | OUTPUT0(3) |
		INPUT(4) | OUTPUT0(5) | OUTPUT0(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_J3_OFFSET */
		INPUT(0) | INPUT(1) | OUTPUT0(2) | OUTPUT0(3) |
		INPUT(4) | INPUT(5) | INPUT(6) | INPUT(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5) | PULL_DIS(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_GPIO_J4_OFFSET */
		INPUT(0) | INPUT(1) | OUTPUT0(2) | INPUT(3) |
		OUTPUT0(4),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110(ARIES)_MP0_1_OFFSET */
		/* XM0CSN[4]: MP0_1[4] -> output high */
		PDNCON_NC(0) | OUTPUT0(1) | PDNCON_NC(2) | INPUT(3) |
		OUTPUT1(4) | INPUT(5) | PDNCON_NC(6) | PDNCON_NC(7),
		PDNPUD_NC(0) | PULL_DIS(1) | PDNPUD_NC(2) | PULL_DOWN(3) |
		PULL_DIS(4) | PULL_DOWN(5) | PDNPUD_NC(6) | PDNPUD_NC(7),
	}, {	/* S5PC110(ARIES)_MP0_2_OFFSET */
		PDNCON_NC(0) | PDNCON_NC(1) | INPUT(2) | PDNCON_NC(3),
		PDNPUD_NC(0) | PDNPUD_NC(1) | PULL_DIS(2) | PDNPUD_NC(3),
	}, {	/* S5PC110(ARIES)_MP0_3_OFFSET */
		/* XM0FWEN: MP0_3[2] -> output high */
		PDNCON_NC(0) | PDNCON_NC(1) | OUTPUT1(2) | INPUT(3) |
		INPUT(4) | OUTPUT1(5) | PDNCON_NC(6) | PDNCON_NC(7),
		PDNPUD_NC(0) | PDNPUD_NC(1) | PULL_DIS(2) | PULL_DOWN(3) |
		PULL_DIS(4) | PULL_DIS(5) | PDNPUD_NC(6) | PDNPUD_NC(7),
	}, {	/* S5PC110(ARIES)_MP0_4_OFFSET */
		PDNCON_NC(0) | OUTPUT0(1) | OUTPUT0(2) | INPUT(3) |
		PDNCON_NC(4) | PDNCON_NC(5) | OUTPUT0(6) | PDNCON_NC(7),
		PDNPUD_NC(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DOWN(3) |
		PDNPUD_NC(4) | PDNPUD_NC(5) | PULL_DIS(6) | PDNPUD_NC(7),
	}, {	/* S5PC110(ARIES)_MP0_5_OFFSET */
		INPUT(0) | INPUT(1) | INPUT(2) | INPUT(3) |
		INPUT(4) | OUTPUT0(5) | INPUT(6) | OUTPUT0(7),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DOWN(4) | PULL_DIS(5) | PULL_UP(6) | PULL_DIS(7),
	}, {	/* S5PC110(ARIES)_MP0_6_OFFSET */
		PDNCON_NC(0) | PDNCON_NC(1) | PDNCON_NC(2) | PDNCON_NC(3) |
		PDNCON_NC(4) | PDNCON_NC(5) | PDNCON_NC(6) | PDNCON_NC(7),
		PDNPUD_NC(0) | PDNPUD_NC(1) | PDNPUD_NC(2) | PDNPUD_NC(3) |
		PDNPUD_NC(4) | PDNPUD_NC(5) | PDNPUD_NC(6) | PDNPUD_NC(7),
	}, {	/* S5PC110(ARIES)_MP0_7_OFFSET */
		PDNCON_NC(0) | PDNCON_NC(1) | PDNCON_NC(2) | PDNCON_NC(3) |
		PDNCON_NC(4) | PDNCON_NC(5) | PDNCON_NC(6) | PDNCON_NC(7),
		PDNPUD_NC(0) | PDNPUD_NC(1) | PDNPUD_NC(2) | PDNPUD_NC(3) |
		PDNPUD_NC(4) | PDNPUD_NC(5) | PDNPUD_NC(6) | PDNPUD_NC(7),
	},
};

static struct gpio_external kessler_external_powerdown_modes[] = {
	{	/* S5PC110(ARIES)_GPIO_H0_OFFSET */
		CON_OUTPUT(0) | CON_INPUT(1) | CON_OUTPUT(2) | CON_OUTPUT(3) |
		CON_OUTPUT(4) | CON_OUTPUT(5) | CON_INPUT(6) | CON_IRQ(7),
		DAT_SET(0) | DAT_CLEAR(2) | DAT_CLEAR(3) |
		DAT_CLEAR(4) | DAT_CLEAR(5),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4) | PULL_DIS(5),
	}, {	/* S5PC110(ARIES)_GPIO_H1_OFFSET */
		CON_OUTPUT(0) | CON_OUTPUT(1) | CON_OUTPUT(2) | CON_IRQ(3) |
		CON_OUTPUT(4) | CON_OUTPUT(5) | CON_OUTPUT(6) | CON_INPUT(7),
		DAT_CLEAR(0),
		PULL_DIS(0) | PULL_DIS(1) | PULL_DIS(2) | PULL_DIS(3) |
		PULL_DIS(4),
	}, {	/* S5PC110(ARIES)_GPIO_H2_OFFSET */
		CON_OUTPUT(0) | CON_OUTPUT(1) | CON_OUTPUT(2) | CON_OUTPUT(3) |
		CON_IRQ(4) | CON_IRQ(5) | CON_IRQ(6) | CON_IRQ(7),
		DAT_CLEAR(0) | DAT_CLEAR(1) | DAT_CLEAR(2) | DAT_CLEAR(3),
		0,
	}, {	/* S5PC110(ARIES)_GPIO_H3_OFFSET */
		CON_IRQ(0) | CON_IRQ(1) | CON_IRQ(2) | CON_OUTPUT(3) |
		CON_IRQ(4) | CON_OUTPUT(5) | CON_IRQ(6) | CON_OUTPUT(7),
		DAT_CLEAR(3) | DAT_CLEAR(5) | DAT_CLEAR(7),
		0,
	},
};

#endif /* __GPIO_SETTING_H */
