/*
 * Copyright (c) 2000 - 2011 Samsung Electronics Co., Ltd. All rights reserved.
 * Sanghee Kim <sh0130.kim@samsung.com>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef __TIZEN_GPT_VER08_H__
#define __TIZEN_GPT_VER08_H__

#define DEFAULT_PIT_NUM		18

struct pit_info {
	pit_header_t hdr;
	partition_info_t entry[DEFAULT_PIT_NUM];
};

static struct pit_info default_pit08 = {
	.hdr = {
		.magic = PIT_MAGIC,
		.count = DEFAULT_PIT_NUM,
		.gang_format = {'C', 'O', 'M', '_', 'T', 'A', 'R', '2'},
		.model = {'T', 'I', 'Z', 'E', 'N'},
	},
	.entry[0] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 80,
		.part_type	= PART_TYPE_BOOTLOADER,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0,
		.blk_num	= 568,
		.offset		= 0,
		.file_size	= 0,
		.name		= "s-boot-mmc",
		.file_name	= "s-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[1] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 81,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 256,
		.blk_num	= 312,
		.offset		= 0,
		.file_size	= 0,
		.name		= "tzsw",
		.file_name	= "tz.img",
		.delta_name	= "",
	},
	.entry[2] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 70,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 64,
		.blk_num	= 16,
		.offset		= 0,
		.file_size	= 0,
		.name		= "pit",
		.file_name	= "Tizen_GPT_Ver08.pit",
		.delta_name	= "",
	},
	.entry[3] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 71,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 4224,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "MD5HDR",
		.file_name	= "md5.img",
		.delta_name	= "",
	},
	.entry[4] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 1,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 128,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "u-boot-mmc",
		.file_name	= "u-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[5] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 2,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 2176,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "u-boot-mmc-bak",
		.file_name	= "u-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[6] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 3,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 6272,
		.blk_num	= 512,
		.offset		= 0,
		.file_size	= 0,
		.name		= "params",
		.file_name	= "params.bin",
		.delta_name	= "",
	},
	.entry[7] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 4,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 6784,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "log",
		.file_name	= "log",
		.delta_name	= "",
	},
	.entry[8] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 5,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 8832,
		.blk_num	= 1408,
		.offset		= 0,
		.file_size	= 0,
		.name		= "reserved",
		.file_name	= "reserved",
		.delta_name	= "",
	},
	.entry[9] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 6,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 10240,
		.blk_num	= 16384,
		.offset		= 0,
		.file_size	= 0,
		.name		= "csa-mmc",
		.file_name	= "csa-mmc",
		.delta_name	= "",
	},
	.entry[10] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 7,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 26624,
		.blk_num	= 122880,
		.offset		= 0,
		.file_size	= 0,
		.name		= "boot",
		.file_name	= "boot.img",
		.delta_name	= "",
	},
	.entry[11] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 8,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 149504,
		.blk_num	= 204800,
		.offset		= 0,
		.file_size	= 0,
		.name		= "qboot",
		.file_name	= "qboot.img",
		.delta_name	= "",
	},
	.entry[12] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 9,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 354304,
		.blk_num	= 307200,
		.offset		= 0,
		.file_size	= 0,
		.name		= "csc",
		.file_name	= "csc.img",
		.delta_name	= "",
	},
	.entry[13] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 10,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 661504,
		.blk_num	= 3145728,
		.offset		= 0,
		.file_size	= 0,
		.name		= "platform",
		.file_name	= "platform.img",
		.delta_name	= "",
	},
	.entry[14] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 11,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 3807232,
		.blk_num	= 6144000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "data",
		.file_name	= "data.img",
		.delta_name	= "",
	},
	.entry[15] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 12,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 9951232,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "ums",
		.file_name	= "ums.img",
		.delta_name	= "remained",
	},
	.entry[16] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 13,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "kernel",
		.file_name	= "uImage",
		.delta_name	= "",
	},
	.entry[17] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 14,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "module",
		.file_name	= "modules.img",
		.delta_name	= "",
	},
};

#endif