/*
 * Copyright (c) 2000 - 2011 Samsung Electronics Co., Ltd. All rights reserved.
 * Sanghee Kim <sh0130.kim@samsung.com>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef __TIZEN_GPT_VER10_H__
#define __TIZEN_GPT_VER10_H__

#define DEFAULT_PIT_NUM		23
#define PIT_VERSION		10

struct pit_info {
	pit_header_t hdr;
	partition_info_t entry[DEFAULT_PIT_NUM];
};

static struct pit_info default_pit09 = {
	.hdr = {
		.magic = PIT_MAGIC,
		.count = DEFAULT_PIT_NUM,
		.gang_format = {'C', 'O', 'M', '_', 'T', 'A', 'R', '2'},
		.model = {'T', 'I', 'Z', 'E', 'N'},
	},
	.entry[0] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 80,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x0,
		.blk_num	= 0x238,
		.offset		= 0,
		.file_size	= 0,
		.name		= "s-boot-mmc",
		.file_name	= "s-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[1] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 81,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x100,
		.blk_num	= 0x138,
		.offset		= 0,
		.file_size	= 0,
		.name		= "tzsw",
		.file_name	= "tzdw.bin",
		.delta_name	= "",
	},
	.entry[2] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 90,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x0,
		.blk_num	= 0x800,
		.offset		= 0,
		.file_size	= 0,
		.name		= "u-boot-bak",
		.file_name	= "u-boot-bak.bin",
		.delta_name	= "",
	},
	.entry[3] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 70,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x40,
		.blk_num	= 0x10,
		.offset		= 0,
		.file_size	= 0,
		.name		= "pit",
		.file_name	= "Tizen_GPT_Ver10.pit",
		.delta_name	= "",
	},
	.entry[4] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 71,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x80,
		.blk_num	= 0x800,
		.offset		= 0,
		.file_size	= 0,
		.name		= "u-boot-mmc",
		.file_name	= "u-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[5] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 72,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x880,
		.blk_num	= 0x800,
		.offset		= 0,
		.file_size	= 0,
		.name		= "u-boot-fota",
		.file_name	= "u-boot-fota.bin",
		.delta_name	= "",
	},
	.entry[6] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 73,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x1080,
		.blk_num	= 0x800,
		.offset		= 0,
		.file_size	= 0,
		.name		= "s-boot-sec",
		.file_name	= "s-boot-sec.bin",
		.delta_name	= "",
	},
	.entry[7] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 74,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x1180,
		.blk_num	= 0x138,
		.offset		= 0,
		.file_size	= 0,
		.name		= "tzsw-sec",
		.file_name	= "tzsw-sec.bin",
		.delta_name	= "",
	},
	.entry[8] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 75,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x1880,
		.blk_num	= 0x80,
		.offset		= 0,
		.file_size	= 0,
		.name		= "params",
		.file_name	= "params.bin",
		.delta_name	= "",
	},
	.entry[9] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 76,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x1900,
		.blk_num	= 0x800,
		.offset		= 0,
		.file_size	= 0,
		.name		= "MD5HDR",
		.file_name	= "md5.img",
		.delta_name	= "",
	},
	.entry[10] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 77,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x2100,
		.blk_num	= 0x400,
		.offset		= 0,
		.file_size	= 0,
		.name		= "log",
		.file_name	= "log",
		.delta_name	= "",
	},
	.entry[11] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 78,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0x2500,
		.blk_num	= 0x300,
		.offset		= 0,
		.file_size	= 0,
		.name		= "spare",
		.file_name	= "spare",
		.delta_name	= "",
	},
	.entry[12] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 1,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0x2800,
		.blk_num	= 0x4000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "csa",
		.file_name	= "csa.img",
		.delta_name	= "",
	},
	.entry[13] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 2,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0x6800,
		.blk_num	= 0x32000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "boot",
		.file_name	= "boot.img",
		.delta_name	= "",
	},
	.entry[14] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 3,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0x38800,
		.blk_num	= 0x32000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "qboot",
		.file_name	= "qboot.img",
		.delta_name	= "",
	},
	.entry[15] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 4,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0x6a800,
		.blk_num	= 0x4b000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "csc",
		.file_name	= "csc.img",
		.delta_name	= "",
	},
	.entry[16] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 5,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0xb5800,
		.blk_num	= 0x300000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "rootfs",
		.file_name	= "rootfs.img",
		.delta_name	= "",
	},
	.entry[17] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 6,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0x3b5800,
		.blk_num	= 0x100000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "system-data",
		.file_name	= "system-data.img",
		.delta_name	= "",
	},
	.entry[18] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 7,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0x4b5800,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "user",
		.file_name	= "user.img",
		.delta_name	= "remained",
	},
	.entry[19] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 60,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "kernel",
		.file_name	= "uImage",
		.delta_name	= "",
	},
	.entry[20] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 61,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "module",
		.file_name	= "modules.img",
		.delta_name	= "",
	},
	.entry[21] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 62,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "modem",
		.file_name	= "modem.bin",
		.delta_name	= "",
	},
	.entry[22] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 63,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "fdt",
		.file_name	= "tizen.dtb",
		.delta_name	= "",
	},
};

#endif
