
/*
 * Clock control - Others
 */
#define S5P_OTHERS_REG_BASE(x)		(S5P_PA_CLK_OTHERS + (x))
#define S5P_OTHERS_BASE			S5P_OTHERS_REG_BASE(0x0)
#define S5P_SW_RST			S5P_OTHERS_REG_BASE(0x0)
#define S5P_ONENAND_RST			S5P_OTHERS_REG_BASE(0x8)
#define S5P_GENERAL_CTRL		S5P_OTHERS_REG_BASE(0x100)
#define S5P_GENERAL_STATUS		S5P_OTHERS_REG_BASE(0x104)
#define S5P_MEM_SYS_CFG			S5P_OTHERS_REG_BASE(0x200)
#define S5P_CAM_MUX_SEL			S5P_OTHERS_REG_BASE(0x300)
#define S5P_MIXER_OUT_SEL		S5P_OTHERS_REG_BASE(0x304)
#define S5P_LPMP3_MODE_SEL		S5P_OTHERS_REG_BASE(0x308)
#define S5P_MIPI_PHY_CON0		S5P_OTHERS_REG_BASE(0x400)
#define S5P_MIPI_PHY_CON1		S5P_OTHERS_REG_BASE(0x414)
#define S5P_HDMI_PHY_CON0		S5P_OTHERS_REG_BASE(0x420)

#ifndef __ASSEMBLY__
#define S5P_OTHERS_BASE_REG		__REG(S5P_OTHERS_BASE)
#define S5P_SW_RST_REG			__REG(S5P_SW_RST)
#define S5P_ONENAND_RST_REG		__REG(S5P_ONENAND_RST)
#define S5P_GENERAL_CTRL_REG		__REG(S5P_GENERAL_CTRL)
#define S5P_GENERAL_STATUS_REG		__REG(S5P_GENERAL_STATUS)
#define S5P_MEM_SYS_CFG_REG		__REG(S5P_MEM_SYS_CFG)
#define S5P_CAM_MUX_SEL_REG		__REG(S5P_CAM_MUX_SEL)
#define S5P_MIXER_OUT_SEL_REG		__REG(S5P_MIXER_OUT_SEL)
#define S5P_LPMP3_MODE_SEL_REG		__REG(S5P_LPMP3_MODE_SEL)
#define S5P_MIPI_PHY_CON0_REG		__REG(S5P_MIPI_PHY_CON0)
#define S5P_MIPI_PHY_CON1_REG		__REG(S5P_MIPI_PHY_CON1)
#define S5P_HDMI_PHY_CON0_REG		__REG(S5P_HDMI_PHY_CON0)
#endif	/* __ASSENBLY__ */

