
/* 
 * Watchdog
 */
#define S5P_WATCHDOG_BASE(x)	(S5P_PA_WATCHDOG + (x))

#define WTCON_OFFSET		0x0
#define WTDAT_OFFSET		0x4
#define WTCNT_OFFSET		0x8
#define WTCLRINT_OFFSET		0xc

#define S5P_WTCON		S5P_WATCHDOG_BASE(WTCON_OFFSET)
#define S5P_WTDAT		S5P_WATCHDOG_BASE(WTDAT_OFFSET)
#define S5P_WTCNT		S5P_WATCHDOG_BASE(WTCNT_OFFSET)
#define S5P_WTCLRINT		S5P_WATCHDOG_BASE(WTCLRINT_OFFSET)

