
/* DISPC common */
#define DISPC_REVISION                  DISPC_REG(0x0000)
#define DISPC_SYSCONFIG                 DISPC_REG(0x0010)
#define DISPC_SYSSTATUS                 DISPC_REG(0x0014)
#define DISPC_IRQSTATUS                 DISPC_REG(0x0018)
#define DISPC_IRQENABLE                 DISPC_REG(0x001C)
#define DISPC_CONTROL                   DISPC_REG(0x0040)
#define DISPC_CONFIG                    DISPC_REG(0x0044)
#define DISPC_CAPABLE                   DISPC_REG(0x0048)
#define DISPC_DEFAULT_COLOR0            DISPC_REG(0x004C)
#define DISPC_DEFAULT_COLOR1            DISPC_REG(0x0050)
#define DISPC_TRANS_COLOR0              DISPC_REG(0x0054)
#define DISPC_TRANS_COLOR1              DISPC_REG(0x0058)
#define DISPC_LINE_STATUS               DISPC_REG(0x005C)
#define DISPC_LINE_NUMBER               DISPC_REG(0x0060)
#define DISPC_TIMING_H                  DISPC_REG(0x0064)
#define DISPC_TIMING_V                  DISPC_REG(0x0068)
#define DISPC_POL_FREQ                  DISPC_REG(0x006C)
#define DISPC_DIVISOR1                   DISPC_REG(0x0070)
#define DISPC_GLOBAL_ALPHA              DISPC_REG(0x0074)
#define DISPC_SIZE_DIG                  DISPC_REG(0x0078)
#define DISPC_SIZE_LCD                  DISPC_REG(0x007C)
#define DISPC_GLOBAL_BUFFER             DISPC_REG(0x0800)
#define DISPC_DIVISOR             DISPC_REG(0x0804)

/* DISPC GFX plane */
#define DISPC_GFX_BA0                   DISPC_REG(0x0080)
#define DISPC_GFX_BA1                   DISPC_REG(0x0084)
#define DISPC_GFX_POSITION              DISPC_REG(0x0088)
#define DISPC_GFX_SIZE                  DISPC_REG(0x008C)
#define DISPC_GFX_ATTRIBUTES            DISPC_REG(0x00A0)
#define DISPC_GFX_FIFO_THRESHOLD        DISPC_REG(0x00A4)
#define DISPC_GFX_FIFO_SIZE_STATUS      DISPC_REG(0x00A8)
#define DISPC_GFX_ROW_INC               DISPC_REG(0x00AC)
#define DISPC_GFX_PIXEL_INC             DISPC_REG(0x00B0)
#define DISPC_GFX_WINDOW_SKIP           DISPC_REG(0x00B4)
#define DISPC_GFX_TABLE_BA              DISPC_REG(0x00B8)

#define DISPC_DATA_CYCLE1               DISPC_REG(0x01D4)
#define DISPC_DATA_CYCLE2               DISPC_REG(0x01D8)
#define DISPC_DATA_CYCLE3               DISPC_REG(0x01DC)

/* OMAP4 new global registers */
#define DISPC_CONTROL2          DISPC_REG(0x0238)
#define DISPC_DEFAULT_COLOR2            DISPC_REG(0x03AC)
#define DISPC_TRANS_COLOR2              DISPC_REG(0x03B0)
#define DISPC_CPR2_COEF_B               DISPC_REG(0x03B4)
#define DISPC_CPR2_COEF_G               DISPC_REG(0x03B8)
#define DISPC_CPR2_COEF_R               DISPC_REG(0x03BC)
#define DISPC_DATA2_CYCLE1              DISPC_REG(0x03C0)
#define DISPC_DATA2_CYCLE2              DISPC_REG(0x03C4)
#define DISPC_DATA2_CYCLE3              DISPC_REG(0x03C8)
#define DISPC_SIZE_LCD2         DISPC_REG(0x03CC)
#define DISPC_TIMING_H2         DISPC_REG(0x0400)
#define DISPC_TIMING_V2         DISPC_REG(0x0404)
#define DISPC_POL_FREQ2         DISPC_REG(0x0408)
#define DISPC_DIVISOR2          DISPC_REG(0x040C)
#define DISPC_CONFIG2           DISPC_REG(0x0620)
