
#if defined (__S5PC100_GENERIC_H__)

/*
 * Referenced from linux/arch/arm/plat-s3c/include/plat/ 
 * & linux/arch/arm/plat-s3c6410/include/plat.
 */

//#ifndef __S5PC100_H__
//#define __S5PC100_H__

#include <asm/hardware.h>

#define S5P_ADDR_BASE	(0xe0000000)

#define S5P_ADDR(x)		(S5P_ADDR_BASE + (x))

#define S5P_PA_ID			S5P_ADDR(0x00000000)	/* ID Base */
#define S5P_PA_CLK			S5P_ADDR(0x00100000)	/* Clock Base */
#define S5P_PA_PWR			S5P_ADDR(0x00108000)	/* Power Base */
#define S5P_PA_CLK_OTHERS	S5P_ADDR(0x00200000)	/* Clock Others Base */
#define S5P_PA_GPIO			S5P_ADDR(0x00300000)    /* GPIO Base */
#define S5P_PA_VIC0			S5P_ADDR(0x04000000)    /* Vector Interrupt Controller 0 */
#define S5P_PA_VIC1			S5P_ADDR(0x04100000)    /* Vector Interrupt Controller 1 */
#define S5P_PA_VIC2			S5P_ADDR(0x04200000)    /* Vector Interrupt Controller 2 */
#define S5P_PA_TZIC0		S5P_ADDR(0x05000000)    /* TrustZone Interrupt Controller 0 */
#define S5P_PA_TZIC1		S5P_ADDR(0x05100000)    /* TrustZone Interrupt Controller 1 */
#define S5P_PA_TZIC2		S5P_ADDR(0x05200000)    /* TrustZone Interrupt Controller 2 */
#define S5P_PA_DMC			S5P_ADDR(0x06000000)    /* Dram Memory Controller */
#define S5P_PA_SROMC		S5P_ADDR(0x07000000)    /* SROM Controller */
#define S5P_PA_ONENANDC		S5P_ADDR(0x07100000)    /* OneNand Controller */
#define S5P_PA_PWMTIMER		S5P_ADDR(0x0a000000)    /* PWM Timer */
#define S5P_PA_WATCHDOG		S5P_ADDR(0x0a200000)    /* Watchdog Timer */
#define S5P_PA_SYSTEM		S5P_ADDR(0x0a100000)    /* System Timer */
#define S5P_PA_RTC			S5P_ADDR(0x0a300000)    /* RTC */
#define S5P_PA_UART			S5P_ADDR(0x0c000000)	/* Uart Base */


/* 
 * Chip ID
 */
#define S5P_ID(x)	(S5P_PA_ID + (x))	

#define S5P_PRO_ID		S5P_ID(0)
#define S5P_OMR		S5P_ID(4)


/*
 * Clock control
 */
#define S5P_CLKREG(x)	(S5P_PA_CLK + (x))

#define S5P_APLL_LOCK	S5P_CLKREG(0x0)
#define S5P_MPLL_LOCK	S5P_CLKREG(0x4)
#define S5P_EPLL_LOCK	S5P_CLKREG(0x8)
#define S5P_HPLL_LOCK	S5P_CLKREG(0xc)

#define S5P_APLL_CON	S5P_CLKREG(0x100)
#define S5P_MPLL_CON	S5P_CLKREG(0x104)
#define S5P_EPLL_CON	S5P_CLKREG(0x108)
#define S5P_HPLL_CON	S5P_CLKREG(0x10c)

#define S5P_CLK_SRC0	S5P_CLKREG(0x200)
#define S5P_CLK_SRC1	S5P_CLKREG(0x204)
#define S5P_CLK_SRC2	S5P_CLKREG(0x208)
#define S5P_CLK_SRC3	S5P_CLKREG(0x20c)

#define S5P_CLK_DIV0	S5P_CLKREG(0x300)
#define S5P_CLK_DIV1	S5P_CLKREG(0x304)
#define S5P_CLK_DIV2	S5P_CLKREG(0x308)
#define S5P_CLK_DIV3	S5P_CLKREG(0x30c)
#define S5P_CLK_DIV0	S5P_CLKREG(0x300)

#define S5P_CLK_OUT		S5P_CLKREG(0x400)

#define S5P_CLK_GATE_D00	S5P_CLKREG(0x500)
#define S5P_CLK_GATE_D01	S5P_CLKREG(0x504)
#define S5P_CLK_GATE_D02	S5P_CLKREG(0x508)

#define S5P_CLK_GATE_D10	S5P_CLKREG(0x520)
#define S5P_CLK_GATE_D11	S5P_CLKREG(0x524)
#define S5P_CLK_GATE_D12	S5P_CLKREG(0x528)
#define S5P_CLK_GATE_D13	S5P_CLKREG(0x530)
#define S5P_CLK_GATE_D14	S5P_CLKREG(0x534)

#define S5P_CLK_GATE_D20	S5P_CLKREG(0x540)

#define S5P_CLK_GATE_SCLK0	S5P_CLKREG(0x560)
#define S5P_CLK_GATE_SCLK1	S5P_CLKREG(0x564)


/*
 * Power control
 */
#define S5P_PWRREG(x)	(S5P_PA_PWR + (x))

#define S5P_PWR_CFG				S5P_PWRREG(0x0)
#define S5P_EINT_WAKEUP_MASK	S5P_PWRREG(0x04)
#define S5P_NORMAL_CFG			S5P_PWRREG(0x10)
#define S5P_STOP_CFG			S5P_PWRREG(0x14)
#define S5P_SLEEP_CFG			S5P_PWRREG(0x18)
#define S5P_STOP_MEM_CFG		S5P_PWRREG(0x1c)
#define S5P_OSC_FREQ			S5P_PWRREG(0x100)
#define S5P_OSC_STABLE			S5P_PWRREG(0x104)
#define S5P_PWR_STABLE			S5P_PWRREG(0x108)
#define S5P_INTERNAL_PWR_STABLE	S5P_PWRREG(0x110)
#define S5P_CLAMP_STABLE		S5P_PWRREG(0x114)
#define S5P_OTHERS				S5P_PWRREG(0x200)
#define S5P_RST_STAT			S5P_PWRREG(0x300)
#define S5P_WAKEUP_STAT			S5P_PWRREG(0x304)
#define S5P_BLK_PWR_STAT		S5P_PWRREG(0x308)
#define S5P_INFORM0				S5P_PWRREG(0x400)
#define S5P_INFORM1				S5P_PWRREG(0x404)
#define S5P_INFORM2				S5P_PWRREG(0x408)
#define S5P_INFORM3				S5P_PWRREG(0x40c)
#define S5P_INFORM4				S5P_PWRREG(0x410)
#define S5P_INFORM5				S5P_PWRREG(0x414)
#define S5P_INFORM6				S5P_PWRREG(0x418)
#define S5P_INFORM7				S5P_PWRREG(0x41c)
#define S5P_DCGIDX_MAP0			S5P_PWRREG(0x500)
#define S5P_DCGIDX_MAP1			S5P_PWRREG(0x504)
#define S5P_DCGIDX_MAP2			S5P_PWRREG(0x508)
#define S5P_DCGPERF_MAP0		S5P_PWRREG(0x50c)
#define S5P_DCGPERF_MAP1		S5P_PWRREG(0x510)
#define S5P_DVCIDX_MAP			S5P_PWRREG(0x514)
#define S5P_FREQ_CPU			S5P_PWRREG(0x518)
#define S5P_FREQ_DPM			S5P_PWRREG(0x51c)
#define S5P_DVSEMCLK_EN			S5P_PWRREG(0x520)
#define S5P_APLL_CON_L8			S5P_PWRREG(0x600)
#define S5P_APLL_CON_L7			S5P_PWRREG(0x604)
#define S5P_APLL_CON_L6			S5P_PWRREG(0x608)
#define S5P_APLL_CON_L5			S5P_PWRREG(0x60c)
#define S5P_APLL_CON_L4			S5P_PWRREG(0x610)
#define S5P_APLL_CON_L3			S5P_PWRREG(0x614)
#define S5P_APLL_CON_L2			S5P_PWRREG(0x618)
#define S5P_APLL_CON_L1			S5P_PWRREG(0x61c)
#define S5P_EM_CONTROL			S5P_PWRREG(0x620)

#define S5P_CLKDIV_IEM_L8		S5P_PWRREG(0x700)
#define S5P_CLKDIV_IEM_L7		S5P_PWRREG(0x704)
#define S5P_CLKDIV_IEM_L6		S5P_PWRREG(0x708)
#define S5P_CLKDIV_IEM_L5		S5P_PWRREG(0x70c)
#define S5P_CLKDIV_IEM_L4		S5P_PWRREG(0x710)
#define S5P_CLKDIV_IEM_L3		S5P_PWRREG(0x714)
#define S5P_CLKDIV_IEM_L2		S5P_PWRREG(0x718)
#define S5P_CLKDIV_IEM_L1		S5P_PWRREG(0x71c)

#define S5P_IEM_HPMCLK_DIV		S5P_PWRREG(0x724)


/*
 * Clock control - Others
 */
#define S5P_OTHERS_REG(x)		(S5P_PA_CLK_OTHERS + (x))

#define S5P_SW_RST				S5P_OTHERS_REG(0x0)
#define S5P_ONENAND_RST		S5P_OTHERS_REG(0x8)

#define S5P_GENERAL_CTRL		S5P_OTHERS_REG(0x100)
#define S5P_GENERAL_STATUS		S5P_OTHERS_REG(0x104)

#define S5P_MEM_SYS_CFG		S5P_OTHERS_REG(0x200)

#define S5P_CAM_MUX_SEL		S5P_OTHERS_REG(0x300)
#define S5P_MIXER_OUT_SEL		S5P_OTHERS_REG(0x304)
#define S5P_LPMP3_MODE_SEL		S5P_OTHERS_REG(0x308)

#define S5P_MIPI_PHY_CON0		S5P_OTHERS_REG(0x400)
#define S5P_MIPI_PHY_CON1		S5P_OTHERS_REG(0x414)
#define S5P_HDMI_PHY_CON0		S5P_OTHERS_REG(0x420)


/* 
 * GPIO
 */

/* GPIO Bank Base */
#define S5P_GPIO_BASE(x)			(S5P_PA_GPIO + (x))

#define S5P_GPIO_A_REG(x)			(S5P_GPIO_BASE(0x0) + (x))
#define S5P_GPIO_B_REG(x)			(S5P_GPIO_BASE(0x40) + (x))
#define S5P_GPIO_C_REG(x)			(S5P_GPIO_BASE(0x60) + (x))
#define S5P_GPIO_D_REG(x)			(S5P_GPIO_BASE(0x80) + (x))
#define S5P_GPIO_E_REG(x)			(S5P_GPIO_BASE(0xa0) + (x))
#define S5P_GPIO_F_REG(x)			(S5P_GPIO_BASE(0xe0) + (x))
#define S5P_GPIO_G_REG(x)			(S5P_GPIO_BASE(0x160) + (x))
#define S5P_GPIO_I_REG(x)			(S5P_GPIO_BASE(0x1e0) + (x))
#define S5P_GPIO_J_REG(x)			(S5P_GPIO_BASE(0x200) + (x))
#define S5P_GPIO_K_REG(x)			(S5P_GPIO_BASE(0x2a0) + (x))
#define S5P_GPIO_L_REG(x)			(S5P_GPIO_BASE(0x320) + (x))

#define S5P_MP_REG(x)				(S5P_GPIO_BASE(0x3c0) + (x))
#define S5P_ETC_REG(x)				(S5P_GPIO_BASE(0x4e0) + (x))

#define S5P_GPIO_INT_CON_REG(x)	(S5P_GPIO_BASE(0x700) + (x))
#define S5P_GPIO_INT_FLTCON_REG(x)	(S5P_GPIO_BASE(0x800) + (x))
#define S5P_GPIO_INT_MASK_REG(x)	(S5P_GPIO_BASE(0x900) + (x))
#define S5P_GPIO_INT_PEND_REG(x)	(S5P_GPIO_BASE(0xa00) + (x))
#define S5P_GPIO_INT_PRIO_REG(x)	(S5P_GPIO_BASE(0xb00) + (x))

#define S5P_GPIO_H_REG(x)			(S5P_GPIO_BASE(0xc00) + (x))

#define S5P_WAKEUP_INT_CON(x)		(S5P_GPIO_BASE(0xe00) + (x))
#define S5P_WAKEUP_FLTINT_CON(x)	(S5P_GPIO_BASE(0xe80) + (x))
#define S5P_WAKEUP_INT_MASK(x)		(S5P_GPIO_BASE(0xf00) + (x))
#define S5P_WAKEUP_INT_PEND(x)		(S5P_GPIO_BASE(0xf40) + (x))


/* GPIO Offset */
#define CON_OFFSET		0x0
#define DAT_OFFSET		0x4
#define PULL_OFFSET		0x8
#define DRV_OFFSET		0xc
#define PDNCON_OFFSET	0x10
#define PDNPULL_OFFSET	0x14


/* GPIO A Bank Base */
#define S5P_GPIO_A0_BASE(x)		(S5P_GPIO_A_REG(0x0) + (x))
#define S5P_GPIO_A1_BASE(x)		(S5P_GPIO_A_REG(0x20) + (x))

#define S5P_GPIO_A0_CON			S5P_GPIO_A0_BASE(CON_OFFSET)
#define S5P_GPIO_A0_DAT			S5P_GPIO_A0_BASE(DAT_OFFSET)
#define S5P_GPIO_A0_PULL			S5P_GPIO_A0_BASE(PULL_OFFSET)
#define S5P_GPIO_A0_DRV			S5P_GPIO_A0_BASE(DRV_OFFSET)
#define S5P_GPIO_A0_PDNCON			S5P_GPIO_A0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_A0_PDNPUL			S5P_GPIO_A0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_A1_CON			S5P_GPIO_A1_BASE(CON_OFFSET)
#define S5P_GPIO_A1_DAT			S5P_GPIO_A1_BASE(DAT_OFFSET)
#define S5P_GPIO_A1_PULL			S5P_GPIO_A1_BASE(PULL_OFFSET)
#define S5P_GPIO_A1_DRV			S5P_GPIO_A1_BASE(DRV_OFFSET)
#define S5P_GPIO_A1_PDNCON			S5P_GPIO_A1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_A1_PDNPUL			S5P_GPIO_A1_BASE(PDNPULL_OFFSET)

/* GPIO B Bank Base */
#define S5P_GPIO_B_BASE(x)			(S5P_GPIO_B_REG(0x0) + (x))

#define S5P_GPIO_B_CON				S5P_GPIO_B_BASE(CON_OFFSET)
#define S5P_GPIO_B_DAT				S5P_GPIO_B_BASE(DAT_OFFSET)
#define S5P_GPIO_B_PULL			S5P_GPIO_B_BASE(PULL_OFFSET)
#define S5P_GPIO_B_DRV				S5P_GPIO_B_BASE(DRV_OFFSET)
#define S5P_GPIO_B_PDNCON			S5P_GPIO_B_BASE(PDNCON_OFFSET)
#define S5P_GPIO_B_PDNPUL			S5P_GPIO_B_BASE(PDNPULL_OFFSET)

/* GPIO C Bank Base */
#define S5P_GPIO_C_BASE(x)			(S5P_GPIO_C_REG(0x0) + (x))

#define S5P_GPIO_C_CON				S5P_GPIO_C_BASE(CON_OFFSET)
#define S5P_GPIO_C_DAT				S5P_GPIO_C_BASE(DAT_OFFSET)
#define S5P_GPIO_C_PULL			S5P_GPIO_C_BASE(PULL_OFFSET)
#define S5P_GPIO_C_DRV				S5P_GPIO_C_BASE(DRV_OFFSET)
#define S5P_GPIO_C_PDNCON			S5P_GPIO_C_BASE(PDNCON_OFFSET)
#define S5P_GPIO_C_PDNPUL			S5P_GPIO_C_BASE(PDNPULL_OFFSET)

/* GPIO D Bank Base */
#define S5P_GPIO_D_BASE(x)			(S5P_GPIO_C_REG(0x0) + (x))

#define S5P_GPIO_D_CON				S5P_GPIO_C_BASE(CON_OFFSET)
#define S5P_GPIO_D_DAT				S5P_GPIO_C_BASE(DAT_OFFSET)
#define S5P_GPIO_D_PULL			S5P_GPIO_C_BASE(PULL_OFFSET)
#define S5P_GPIO_D_DRV				S5P_GPIO_C_BASE(DRV_OFFSET)
#define S5P_GPIO_D_PDNCON			S5P_GPIO_C_BASE(PDNCON_OFFSET)
#define S5P_GPIO_D_PDNPUL			S5P_GPIO_C_BASE(PDNPULL_OFFSET)

/* GPIO E Bank Base */
#define S5P_GPIO_E0_BASE(x)		(S5P_GPIO_E_REG(0x0) + (x))
#define S5P_GPIO_E1_BASE(x)		(S5P_GPIO_E_REG(0x20) + (x))

#define S5P_GPIO_E0_CON			S5P_GPIO_E0_BASE(CON_OFFSET)
#define S5P_GPIO_E0_DAT			S5P_GPIO_E0_BASE(DAT_OFFSET)
#define S5P_GPIO_E0_PULL			S5P_GPIO_E0_BASE(PULL_OFFSET)
#define S5P_GPIO_E0_DRV			S5P_GPIO_E0_BASE(DRV_OFFSET)
#define S5P_GPIO_E0_PDNCON			S5P_GPIO_E0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_E0_PDNPUL			S5P_GPIO_E0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_E1_CON			S5P_GPIO_E1_BASE(CON_OFFSET)
#define S5P_GPIO_E1_DAT			S5P_GPIO_E1_BASE(DAT_OFFSET)
#define S5P_GPIO_E1_PULL			S5P_GPIO_E1_BASE(PULL_OFFSET)
#define S5P_GPIO_E1_DRV			S5P_GPIO_E1_BASE(DRV_OFFSET)
#define S5P_GPIO_E1_PDNCON			S5P_GPIO_E1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_E1_PDNPUL			S5P_GPIO_E1_BASE(PDNPULL_OFFSET)

/* GPIO F Bank Base */
#define S5P_GPIO_F0_BASE(x)		(S5P_GPIO_F_REG(0x0) + (x))
#define S5P_GPIO_F1_BASE(x)		(S5P_GPIO_F_REG(0x20) + (x))
#define S5P_GPIO_F2_BASE(x)		(S5P_GPIO_F_REG(0x40) + (x))
#define S5P_GPIO_F3_BASE(x)		(S5P_GPIO_F_REG(0x60) + (x))

#define S5P_GPIO_F0_CON			S5P_GPIO_F0_BASE(CON_OFFSET)
#define S5P_GPIO_F0_DAT			S5P_GPIO_F0_BASE(DAT_OFFSET)
#define S5P_GPIO_F0_PULL			S5P_GPIO_F0_BASE(PULL_OFFSET)
#define S5P_GPIO_F0_DRV			S5P_GPIO_F0_BASE(DRV_OFFSET)
#define S5P_GPIO_F0_PDNCON			S5P_GPIO_F0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_F0_PDNPUL			S5P_GPIO_F0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_F1_CON			S5P_GPIO_F1_BASE(CON_OFFSET)
#define S5P_GPIO_F1_DAT			S5P_GPIO_F1_BASE(DAT_OFFSET)
#define S5P_GPIO_F1_PULL			S5P_GPIO_F1_BASE(PULL_OFFSET)
#define S5P_GPIO_F1_DRV			S5P_GPIO_F1_BASE(DRV_OFFSET)
#define S5P_GPIO_F1_PDNCON			S5P_GPIO_F1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_F1_PDNPUL			S5P_GPIO_F1_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_F2_CON			S5P_GPIO_F2_BASE(CON_OFFSET)
#define S5P_GPIO_F2_DAT			S5P_GPIO_F2_BASE(DAT_OFFSET)
#define S5P_GPIO_F2_PULL			S5P_GPIO_F2_BASE(PULL_OFFSET)
#define S5P_GPIO_F2_DRV			S5P_GPIO_F2_BASE(DRV_OFFSET)
#define S5P_GPIO_F2_PDNCON			S5P_GPIO_F2_BASE(PDNCON_OFFSET)
#define S5P_GPIO_F2_PDNPUL			S5P_GPIO_F2_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_F3_CON			S5P_GPIO_F3_BASE(CON_OFFSET)
#define S5P_GPIO_F3_DAT			S5P_GPIO_F3_BASE(DAT_OFFSET)
#define S5P_GPIO_F3_PULL			S5P_GPIO_F3_BASE(PULL_OFFSET)
#define S5P_GPIO_F3_DRV			S5P_GPIO_F3_BASE(DRV_OFFSET)
#define S5P_GPIO_F3_PDNCON			S5P_GPIO_F3_BASE(PDNCON_OFFSET)
#define S5P_GPIO_F3_PDNPUL			S5P_GPIO_F3_BASE(PDNPULL_OFFSET)

/* GPIO G Bank Base */
#define S5P_GPIO_G0_BASE(x)		(S5P_GPIO_G_REG(0x0) + (x))
#define S5P_GPIO_G1_BASE(x)		(S5P_GPIO_G_REG(0x20) + (x))
#define S5P_GPIO_G2_BASE(x)		(S5P_GPIO_G_REG(0x40) + (x))
#define S5P_GPIO_G3_BASE(x)		(S5P_GPIO_G_REG(0x60) + (x))

#define S5P_GPIO_G0_CON			S5P_GPIO_G0_BASE(CON_OFFSET)
#define S5P_GPIO_G0_DAT			S5P_GPIO_G0_BASE(DAT_OFFSET)
#define S5P_GPIO_G0_PULL			S5P_GPIO_G0_BASE(PULL_OFFSET)
#define S5P_GPIO_G0_DRV			S5P_GPIO_G0_BASE(DRV_OFFSET)
#define S5P_GPIO_G0_PDNCON			S5P_GPIO_G0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_G0_PDNPUL			S5P_GPIO_G0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_G1_CON			S5P_GPIO_G1_BASE(CON_OFFSET)
#define S5P_GPIO_G1_DAT			S5P_GPIO_G1_BASE(DAT_OFFSET)
#define S5P_GPIO_G1_PULL			S5P_GPIO_G1_BASE(PULL_OFFSET)
#define S5P_GPIO_G1_DRV			S5P_GPIO_G1_BASE(DRV_OFFSET)
#define S5P_GPIO_G1_PDNCON			S5P_GPIO_G1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_G1_PDNPUL			S5P_GPIO_G1_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_G2_CON			S5P_GPIO_G2_BASE(CON_OFFSET)
#define S5P_GPIO_G2_DAT			S5P_GPIO_G2_BASE(DAT_OFFSET)
#define S5P_GPIO_G2_PULL			S5P_GPIO_G2_BASE(PULL_OFFSET)
#define S5P_GPIO_G2_DRV			S5P_GPIO_G2_BASE(DRV_OFFSET)
#define S5P_GPIO_G2_PDNCON			S5P_GPIO_G2_BASE(PDNCON_OFFSET)
#define S5P_GPIO_G2_PDNPUL			S5P_GPIO_G2_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_G3_CON			S5P_GPIO_G3_BASE(CON_OFFSET)
#define S5P_GPIO_G3_DAT			S5P_GPIO_G3_BASE(DAT_OFFSET)
#define S5P_GPIO_G3_PULL			S5P_GPIO_G3_BASE(PULL_OFFSET)
#define S5P_GPIO_G3_DRV			S5P_GPIO_G3_BASE(DRV_OFFSET)
#define S5P_GPIO_G3_PDNCON			S5P_GPIO_G3_BASE(PDNCON_OFFSET)
#define S5P_GPIO_G3_PDNPUL			S5P_GPIO_G3_BASE(PDNPULL_OFFSET)

/* GPIO I Bank Base */
#define S5P_GPIO_I_BASE(x)			(S5P_GPIO_I_REG(0x0) + (x))

#define S5P_GPIO_I_CON				S5P_GPIO_I_BASE(CON_OFFSET)
#define S5P_GPIO_I_DAT				S5P_GPIO_I_BASE(DAT_OFFSET)
#define S5P_GPIO_I_PULL			S5P_GPIO_I_BASE(PULL_OFFSET)
#define S5P_GPIO_I_DRV				S5P_GPIO_I_BASE(DRV_OFFSET)
#define S5P_GPIO_I_PDNCON			S5P_GPIO_I_BASE(PDNCON_OFFSET)
#define S5P_GPIO_I_PDNPUL			S5P_GPIO_I_BASE(PDNPULL_OFFSET)

/* GPIO J Bank Base */
#define S5P_GPIO_J0_BASE(x)		(S5P_GPIO_J_REG(0x0) + (x))
#define S5P_GPIO_J1_BASE(x)		(S5P_GPIO_J_REG(0x20) + (x))
#define S5P_GPIO_J2_BASE(x)		(S5P_GPIO_J_REG(0x40) + (x))
#define S5P_GPIO_J3_BASE(x)		(S5P_GPIO_J_REG(0x60) + (x))
#define S5P_GPIO_J4_BASE(x)		(S5P_GPIO_J_REG(0x80) + (x))

#define S5P_GPIO_J0_CON			S5P_GPIO_J0_BASE(CON_OFFSET)
#define S5P_GPIO_J0_DAT			S5P_GPIO_J0_BASE(DAT_OFFSET)
#define S5P_GPIO_J0_PULL			S5P_GPIO_J0_BASE(PULL_OFFSET)
#define S5P_GPIO_J0_DRV			S5P_GPIO_J0_BASE(DRV_OFFSET)
#define S5P_GPIO_J0_PDNCON			S5P_GPIO_J0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_J0_PDNPUL			S5P_GPIO_J0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_J1_CON			S5P_GPIO_J1_BASE(CON_OFFSET)
#define S5P_GPIO_J1_DAT			S5P_GPIO_J1_BASE(DAT_OFFSET)
#define S5P_GPIO_J1_PULL			S5P_GPIO_J1_BASE(PULL_OFFSET)
#define S5P_GPIO_J1_DRV			S5P_GPIO_J1_BASE(DRV_OFFSET)
#define S5P_GPIO_J1_PDNCON			S5P_GPIO_J1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_J1_PDNPUL			S5P_GPIO_J1_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_J2_CON			S5P_GPIO_J2_BASE(CON_OFFSET)
#define S5P_GPIO_J2_DAT			S5P_GPIO_J2_BASE(DAT_OFFSET)
#define S5P_GPIO_J2_PULL			S5P_GPIO_J2_BASE(PULL_OFFSET)
#define S5P_GPIO_J2_DRV			S5P_GPIO_J2_BASE(DRV_OFFSET)
#define S5P_GPIO_J2_PDNCON			S5P_GPIO_J2_BASE(PDNCON_OFFSET)
#define S5P_GPIO_J2_PDNPUL			S5P_GPIO_J2_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_J3_CON			S5P_GPIO_J3_BASE(CON_OFFSET)
#define S5P_GPIO_J3_DAT			S5P_GPIO_J3_BASE(DAT_OFFSET)
#define S5P_GPIO_J3_PULL			S5P_GPIO_J3_BASE(PULL_OFFSET)
#define S5P_GPIO_J3_DRV			S5P_GPIO_J3_BASE(DRV_OFFSET)
#define S5P_GPIO_J3_PDNCON			S5P_GPIO_J3_BASE(PDNCON_OFFSET)
#define S5P_GPIO_J3_PDNPUL			S5P_GPIO_J3_BASE(PDNPULL_OFFSET) 

#define S5P_GPIO_J4_CON			S5P_GPIO_J4_BASE(CON_OFFSET)
#define S5P_GPIO_J4_DAT			S5P_GPIO_J4_BASE(DAT_OFFSET)
#define S5P_GPIO_J4_PULL			S5P_GPIO_J4_BASE(PULL_OFFSET)
#define S5P_GPIO_J4_DRV			S5P_GPIO_J4_BASE(DRV_OFFSET)
#define S5P_GPIO_J4_PDNCON			S5P_GPIO_J4_BASE(PDNCON_OFFSET)
#define S5P_GPIO_J4_PDNPUL			S5P_GPIO_J4_BASE(PDNPULL_OFFSET) 

/* GPIO K Bank Base */
#define S5P_GPIO_K0_BASE(x)		(S5P_GPIO_K_REG(0x0) + (x))
#define S5P_GPIO_K1_BASE(x)		(S5P_GPIO_K_REG(0x20) + (x))
#define S5P_GPIO_K2_BASE(x)		(S5P_GPIO_K_REG(0x40) + (x))
#define S5P_GPIO_K3_BASE(x)		(S5P_GPIO_K_REG(0x60) + (x))

#define S5P_GPIO_K0_CON			S5P_GPIO_K0_BASE(CON_OFFSET)
#define S5P_GPIO_K0_DAT			S5P_GPIO_K0_BASE(DAT_OFFSET)
#define S5P_GPIO_K0_PULL			S5P_GPIO_K0_BASE(PULL_OFFSET)
#define S5P_GPIO_K0_DRV			S5P_GPIO_K0_BASE(DRV_OFFSET)
#define S5P_GPIO_K0_PDNCON			S5P_GPIO_K0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_K0_PDNPUL			S5P_GPIO_K0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_K1_CON			S5P_GPIO_K1_BASE(CON_OFFSET)
#define S5P_GPIO_K1_DAT			S5P_GPIO_K1_BASE(DAT_OFFSET)
#define S5P_GPIO_K1_PULL			S5P_GPIO_K1_BASE(PULL_OFFSET)
#define S5P_GPIO_K1_DRV			S5P_GPIO_K1_BASE(DRV_OFFSET)
#define S5P_GPIO_K1_PDNCON			S5P_GPIO_K1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_K1_PDNPUL			S5P_GPIO_K1_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_K2_CON			S5P_GPIO_K2_BASE(CON_OFFSET)
#define S5P_GPIO_K2_DAT			S5P_GPIO_K2_BASE(DAT_OFFSET)
#define S5P_GPIO_K2_PULL			S5P_GPIO_K2_BASE(PULL_OFFSET)
#define S5P_GPIO_K2_DRV			S5P_GPIO_K2_BASE(DRV_OFFSET)
#define S5P_GPIO_K2_PDNCON			S5P_GPIO_K2_BASE(PDNCON_OFFSET)
#define S5P_GPIO_K2_PDNPUL			S5P_GPIO_K2_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_K3_CON			S5P_GPIO_K3_BASE(CON_OFFSET)
#define S5P_GPIO_K3_DAT			S5P_GPIO_K3_BASE(DAT_OFFSET)
#define S5P_GPIO_K3_PULL			S5P_GPIO_K3_BASE(PULL_OFFSET)
#define S5P_GPIO_K3_DRV			S5P_GPIO_K3_BASE(DRV_OFFSET)
#define S5P_GPIO_K3_PDNCON			S5P_GPIO_K3_BASE(PDNCON_OFFSET)
#define S5P_GPIO_K3_PDNPUL			S5P_GPIO_K3_BASE(PDNPULL_OFFSET) 

/* GPIO L Bank */
#define S5P_GPIO_L0_BASE(x)		(S5P_GPIO_L_REG(0x0) + (x))
#define S5P_GPIO_L1_BASE(x)		(S5P_GPIO_L_REG(0x20) + (x))
#define S5P_GPIO_L2_BASE(x)		(S5P_GPIO_L_REG(0x40) + (x))
#define S5P_GPIO_L3_BASE(x)		(S5P_GPIO_L_REG(0x60) + (x))
#define S5P_GPIO_L4_BASE(x)		(S5P_GPIO_L_REG(0x80) + (x))

#define S5P_GPIO_L0_CON			S5P_GPIO_L0_BASE(CON_OFFSET)
#define S5P_GPIO_L0_DAT			S5P_GPIO_L0_BASE(DAT_OFFSET)
#define S5P_GPIO_L0_PULL			S5P_GPIO_L0_BASE(PULL_OFFSET)
#define S5P_GPIO_L0_DRV			S5P_GPIO_L0_BASE(DRV_OFFSET)
#define S5P_GPIO_L0_PDNCON			S5P_GPIO_L0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_L0_PDNPUL			S5P_GPIO_L0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_L1_CON			S5P_GPIO_L1_BASE(CON_OFFSET)
#define S5P_GPIO_L1_DAT			S5P_GPIO_L1_BASE(DAT_OFFSET)
#define S5P_GPIO_L1_PULL			S5P_GPIO_L1_BASE(PULL_OFFSET)
#define S5P_GPIO_L1_DRV			S5P_GPIO_L1_BASE(DRV_OFFSET)
#define S5P_GPIO_L1_PDNCON			S5P_GPIO_L1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_L1_PDNPUL			S5P_GPIO_L1_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_L2_CON			S5P_GPIO_L2_BASE(CON_OFFSET)
#define S5P_GPIO_L2_DAT			S5P_GPIO_L2_BASE(DAT_OFFSET)
#define S5P_GPIO_L2_PULL			S5P_GPIO_L2_BASE(PULL_OFFSET)
#define S5P_GPIO_L2_DRV			S5P_GPIO_L2_BASE(DRV_OFFSET)
#define S5P_GPIO_L2_PDNCON			S5P_GPIO_L2_BASE(PDNCON_OFFSET)
#define S5P_GPIO_L2_PDNPUL			S5P_GPIO_L2_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_L3_CON			S5P_GPIO_L3_BASE(CON_OFFSET)
#define S5P_GPIO_L3_DAT			S5P_GPIO_L3_BASE(DAT_OFFSET)
#define S5P_GPIO_L3_PULL			S5P_GPIO_L3_BASE(PULL_OFFSET)
#define S5P_GPIO_L3_DRV			S5P_GPIO_L3_BASE(DRV_OFFSET)
#define S5P_GPIO_L3_PDNCON			S5P_GPIO_L3_BASE(PDNCON_OFFSET)
#define S5P_GPIO_L3_PDNPUL			S5P_GPIO_L3_BASE(PDNPULL_OFFSET) 

#define S5P_GPIO_L4_CON			S5P_GPIO_L4_BASE(CON_OFFSET)
#define S5P_GPIO_L4_DAT			S5P_GPIO_L4_BASE(DAT_OFFSET)
#define S5P_GPIO_L4_PULL			S5P_GPIO_L4_BASE(PULL_OFFSET)
#define S5P_GPIO_L4_DRV			S5P_GPIO_L4_BASE(DRV_OFFSET)
#define S5P_GPIO_L4_PDNCON			S5P_GPIO_L4_BASE(PDNCON_OFFSET)
#define S5P_GPIO_L4_PDNPUL			S5P_GPIO_L4_BASE(PDNPULL_OFFSET) 

/* GPIO MP Bank */ 
#define S5P_MP_0_BASE(x)			(S5P_MP_REG(0x0) + (x))
#define S5P_MP_1_BASE(x)			(S5P_MP_REG(0x20) + (x))
#define S5P_MP_2_BASE(x)			(S5P_MP_REG(0x40) + (x))
#define S5P_MP_3_BASE(x)			(S5P_MP_REG(0x60) + (x))
#define S5P_MP_4_BASE(x)			(S5P_MP_REG(0x80) + (x))
#define S5P_MP_5_BASE(x)			(S5P_MP_REG(0xa0) + (x))
#define S5P_MP_6_BASE(x)			(S5P_MP_REG(0xc0) + (x))
#define S5P_MP_7_BASE(x)			(S5P_MP_REG(0xe0) + (x))

#define S5P_MP_0PULL				S5P_MP_0_BASE(PULL_OFFSET)
#define S5P_MP_0DRV				S5P_MP_0_BASE(DRV_OFFSET)
#define S5P_MP_0PDNPULL			S5P_MP_0_BASE(PDNPULL_OFFSET)

#define S5P_MP_1PULL				S5P_MP_1_BASE(PULL_OFFSET)
#define S5P_MP_1DRV				S5P_MP_1_BASE(DRV_OFFSET)
#define S5P_MP_1PDNPULL			S5P_MP_1_BASE(PDNPULL_OFFSET)

#define S5P_MP_2PULL				S5P_MP_2_BASE(PULL_OFFSET)
#define S5P_MP_2DRV				S5P_MP_2_BASE(DRV_OFFSET)
#define S5P_MP_2PDNPULL			S5P_MP_2_BASE(PDNPULL_OFFSET)

#define S5P_MP_3DRV				S5P_MP_3_BASE(DRV_OFFSET)
#define S5P_MP_4DRV				S5P_MP_4_BASE(DRV_OFFSET)
#define S5P_MP_5DRV				S5P_MP_5_BASE(DRV_OFFSET)
#define S5P_MP_6DRV				S5P_MP_6_BASE(DRV_OFFSET)
#define S5P_MP_7DRV				S5P_MP_7_BASE(DRV_OFFSET)
#define S5P_MP_8DRV				S5P_MP_8_BASE(DRV_OFFSET)

/* GPIO ETC Bank */ 
#define S5P_ETC0_BASE(x)			(S5P_ETC_REG(0x0) + (x))
#define S5P_ETC1_BASE(x)			(S5P_ETC_REG(0x20) + (x))
#define S5P_ETC2_BASE(x)			(S5P_ETC_REG(0x40) + (x))
#define S5P_ETC3_BASE(x)			(S5P_ETC_REG(0x60) + (x))
#define S5P_ETC4_BASE(x)			(S5P_ETC_REG(0x80) + (x))

#define S5P_ETC0PULL				S5P_ETC0_BASE(PULL_OFFSET)
#define S5P_ETC0DRV				S5P_ETC0_BASE(DRV_OFFSET)
#define S5P_ETC1PULL				S5P_ETC1_BASE(PULL_OFFSET)
#define S5P_ETC1DRV				S5P_ETC1_BASE(DRV_OFFSET)
#define S5P_ETC2PULL				S5P_ETC2_BASE(PULL_OFFSET)
#define S5P_ETC2DRV				S5P_ETC2_BASE(DRV_OFFSET)
#define S5P_ETC3PULL				S5P_ETC3_BASE(PULL_OFFSET)
#define S5P_ETC3DRV				S5P_ETC3_BASE(DRV_OFFSET)
#define S5P_ETC4DRV				S5P_ETC4_BASE(DRV_OFFSET)

/* GPIO External Interrupt */
#define S5P_GPIO_INT0_CON				S5P_GPIO_INT_CON_REG(0x0)
#define S5P_GPIO_INT1_CON				S5P_GPIO_INT_CON_REG(0x4)
#define S5P_GPIO_INT2_CON				S5P_GPIO_INT_CON_REG(0x8)
#define S5P_GPIO_INT3_CON				S5P_GPIO_INT_CON_REG(0xc)
#define S5P_GPIO_INT4_CON				S5P_GPIO_INT_CON_REG(0x10)
#define S5P_GPIO_INT5_CON				S5P_GPIO_INT_CON_REG(0x14)
#define S5P_GPIO_INT6_CON				S5P_GPIO_INT_CON_REG(0x18)
#define S5P_GPIO_INT7_CON				S5P_GPIO_INT_CON_REG(0x1c)
#define S5P_GPIO_INT8_CON				S5P_GPIO_INT_CON_REG(0x20)
#define S5P_GPIO_INT9_CON				S5P_GPIO_INT_CON_REG(0x24)
#define S5P_GPIO_INT10_CON				S5P_GPIO_INT_CON_REG(0x28)
#define S5P_GPIO_INT11_CON				S5P_GPIO_INT_CON_REG(0x2c)
#define S5P_GPIO_INT12_CON				S5P_GPIO_INT_CON_REG(0x30)
#define S5P_GPIO_INT13_CON				S5P_GPIO_INT_CON_REG(0x34)
#define S5P_GPIO_INT14_CON				S5P_GPIO_INT_CON_REG(0x38)
#define S5P_GPIO_INT15_CON				S5P_GPIO_INT_CON_REG(0x3c)
#define S5P_GPIO_INT16_CON				S5P_GPIO_INT_CON_REG(0x40)
#define S5P_GPIO_INT17_CON				S5P_GPIO_INT_CON_REG(0x44)
#define S5P_GPIO_INT18_CON				S5P_GPIO_INT_CON_REG(0x48)
#define S5P_GPIO_INT19_CON				S5P_GPIO_INT_CON_REG(0x4c)
#define S5P_GPIO_INT20_CON				S5P_GPIO_INT_CON_REG(0x50)

#define S5P_GPIO_INT0_FLTCON0			S5P_GPIO_INT_CON_REG(0x0)
#define S5P_GPIO_INT0_FLTCON1			S5P_GPIO_INT_CON_REG(0x4)
#define S5P_GPIO_INT1_FLTCON0			S5P_GPIO_INT_CON_REG(0x8)
#define S5P_GPIO_INT1_FLTCON1			S5P_GPIO_INT_CON_REG(0xc)
#define S5P_GPIO_INT2_FLTCON0			S5P_GPIO_INT_CON_REG(0x10)
#define S5P_GPIO_INT2_FLTCON1			S5P_GPIO_INT_CON_REG(0x14)
#define S5P_GPIO_INT3_FLTCON0			S5P_GPIO_INT_CON_REG(0x18)
#define S5P_GPIO_INT3_FLTCON1			S5P_GPIO_INT_CON_REG(0x1c)
#define S5P_GPIO_INT4_FLTCON0			S5P_GPIO_INT_CON_REG(0x20)
#define S5P_GPIO_INT4_FLTCON1			S5P_GPIO_INT_CON_REG(0x24)
#define S5P_GPIO_INT5_FLTCON0			S5P_GPIO_INT_CON_REG(0x28)
#define S5P_GPIO_INT5_FLTCON1			S5P_GPIO_INT_CON_REG(0x2c)
#define S5P_GPIO_INT6_FLTCON0			S5P_GPIO_INT_CON_REG(0x30)
#define S5P_GPIO_INT6_FLTCON1			S5P_GPIO_INT_CON_REG(0x34)
#define S5P_GPIO_INT7_FLTCON0			S5P_GPIO_INT_CON_REG(0x38)
#define S5P_GPIO_INT7_FLTCON1			S5P_GPIO_INT_CON_REG(0x3c)
#define S5P_GPIO_INT8_FLTCON0			S5P_GPIO_INT_CON_REG(0x40)
#define S5P_GPIO_INT8_FLTCON1			S5P_GPIO_INT_CON_REG(0x44)
#define S5P_GPIO_INT9_FLTCON0			S5P_GPIO_INT_CON_REG(0x48)
#define S5P_GPIO_INT9_FLTCON1			S5P_GPIO_INT_CON_REG(0x4c)
#define S5P_GPIO_INT10_FLTCON0			S5P_GPIO_INT_CON_REG(0x50)
#define S5P_GPIO_INT11_FLTCON0			S5P_GPIO_INT_CON_REG(0x58)
#define S5P_GPIO_INT11_FLTCON1			S5P_GPIO_INT_CON_REG(0x5c)
#define S5P_GPIO_INT12_FLTCON0			S5P_GPIO_INT_CON_REG(0x60)
#define S5P_GPIO_INT13_FLTCON0			S5P_GPIO_INT_CON_REG(0x68)
#define S5P_GPIO_INT13_FLTCON1			S5P_GPIO_INT_CON_REG(0x6c)
#define S5P_GPIO_INT14_FLTCON0			S5P_GPIO_INT_CON_REG(0x70)
#define S5P_GPIO_INT14_FLTCON1			S5P_GPIO_INT_CON_REG(0x74)
#define S5P_GPIO_INT15_FLTCON0			S5P_GPIO_INT_CON_REG(0x78)
#define S5P_GPIO_INT15_FLTCON1			S5P_GPIO_INT_CON_REG(0x7c)
#define S5P_GPIO_INT16_FLTCON0			S5P_GPIO_INT_CON_REG(0x80)
#define S5P_GPIO_INT16_FLTCON1			S5P_GPIO_INT_CON_REG(0x84)
#define S5P_GPIO_INT17_FLTCON0			S5P_GPIO_INT_CON_REG(0x88)
#define S5P_GPIO_INT17_FLTCON1			S5P_GPIO_INT_CON_REG(0x8c)
#define S5P_GPIO_INT18_FLTCON0			S5P_GPIO_INT_CON_REG(0x90)
#define S5P_GPIO_INT18_FLTCON1			S5P_GPIO_INT_CON_REG(0x94)
#define S5P_GPIO_INT19_FLTCON0			S5P_GPIO_INT_CON_REG(0x98)
#define S5P_GPIO_INT19_FLTCON1			S5P_GPIO_INT_CON_REG(0x9c)
#define S5P_GPIO_INT20_FLTCON0			S5P_GPIO_INT_CON_REG(0xa0)

#define S5P_GPIO_INT0_MASK				S5P_GPIO_INT_MASK_REG(0x00)
#define S5P_GPIO_INT1_MASK				S5P_GPIO_INT_MASK_REG(0x04)
#define S5P_GPIO_INT2_MASK				S5P_GPIO_INT_MASK_REG(0x08)
#define S5P_GPIO_INT3_MASK				S5P_GPIO_INT_MASK_REG(0x0c)
#define S5P_GPIO_INT4_MASK				S5P_GPIO_INT_MASK_REG(0x10)
#define S5P_GPIO_INT5_MASK				S5P_GPIO_INT_MASK_REG(0x14)
#define S5P_GPIO_INT6_MASK				S5P_GPIO_INT_MASK_REG(0x18)
#define S5P_GPIO_INT7_MASK				S5P_GPIO_INT_MASK_REG(0x1c)
#define S5P_GPIO_INT8_MASK				S5P_GPIO_INT_MASK_REG(0x20)
#define S5P_GPIO_INT9_MASK				S5P_GPIO_INT_MASK_REG(0x24)
#define S5P_GPIO_INT10_MASK			S5P_GPIO_INT_MASK_REG(0x28)
#define S5P_GPIO_INT11_MASK			S5P_GPIO_INT_MASK_REG(0x2c)
#define S5P_GPIO_INT12_MASK			S5P_GPIO_INT_MASK_REG(0x30)
#define S5P_GPIO_INT13_MASK			S5P_GPIO_INT_MASK_REG(0x34)
#define S5P_GPIO_INT14_MASK			S5P_GPIO_INT_MASK_REG(0x38)
#define S5P_GPIO_INT15_MASK			S5P_GPIO_INT_MASK_REG(0x3c)
#define S5P_GPIO_INT16_MASK			S5P_GPIO_INT_MASK_REG(0x40)
#define S5P_GPIO_INT17_MASK			S5P_GPIO_INT_MASK_REG(0x44)
#define S5P_GPIO_INT18_MASK			S5P_GPIO_INT_MASK_REG(0x48)
#define S5P_GPIO_INT19_MASK			S5P_GPIO_INT_MASK_REG(0x4c)
#define S5P_GPIO_INT20_MASK			S5P_GPIO_INT_MASK_REG(0x50)

#define S5P_GPIO_INT0_PEND				S5P_GPIO_INT_PEND_REG(0x00)
#define S5P_GPIO_INT1_PEND				S5P_GPIO_INT_PEND_REG(0x04)
#define S5P_GPIO_INT2_PEND				S5P_GPIO_INT_PEND_REG(0x08)
#define S5P_GPIO_INT3_PEND				S5P_GPIO_INT_PEND_REG(0x0c)
#define S5P_GPIO_INT4_PEND				S5P_GPIO_INT_PEND_REG(0x10)
#define S5P_GPIO_INT5_PEND				S5P_GPIO_INT_PEND_REG(0x14)
#define S5P_GPIO_INT6_PEND				S5P_GPIO_INT_PEND_REG(0x18)
#define S5P_GPIO_INT7_PEND				S5P_GPIO_INT_PEND_REG(0x1c)
#define S5P_GPIO_INT8_PEND				S5P_GPIO_INT_PEND_REG(0x20)
#define S5P_GPIO_INT9_PEND				S5P_GPIO_INT_PEND_REG(0x24)
#define S5P_GPIO_INT10_PEND			S5P_GPIO_INT_PEND_REG(0x28)
#define S5P_GPIO_INT11_PEND			S5P_GPIO_INT_PEND_REG(0x2c)
#define S5P_GPIO_INT12_PEND			S5P_GPIO_INT_PEND_REG(0x30)
#define S5P_GPIO_INT13_PEND			S5P_GPIO_INT_PEND_REG(0x34)
#define S5P_GPIO_INT14_PEND			S5P_GPIO_INT_PEND_REG(0x38)
#define S5P_GPIO_INT15_PEND			S5P_GPIO_INT_PEND_REG(0x3c)
#define S5P_GPIO_INT16_PEND			S5P_GPIO_INT_PEND_REG(0x40)
#define S5P_GPIO_INT17_PEND			S5P_GPIO_INT_PEND_REG(0x44)
#define S5P_GPIO_INT18_PEND			S5P_GPIO_INT_PEND_REG(0x48)
#define S5P_GPIO_INT19_PEND			S5P_GPIO_INT_PEND_REG(0x4c)
#define S5P_GPIO_INT20_PEND			S5P_GPIO_INT_PEND_REG(0x50)

#define S5P_GPIO_INT_GRPPRI			S5P_GPIO_INT_PRIO_REG(0x00)
#define S5P_GPIO_INT_PRIORITY			S5P_GPIO_INT_PRIO_REG(0x04)
#define S5P_GPIO_INT_SERVICE			S5P_GPIO_INT_PRIO_REG(0x08)
#define S5P_GPIO_INT_SERVICE_PEND		S5P_GPIO_INT_PRIO_REG(0x0c)
#define S5P_GPIO_INT_GRPFIXPRI			S5P_GPIO_INT_PRIO_REG(0x10)

#define S5P_GPIO_INT0_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x14)
#define S5P_GPIO_INT1_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x18)
#define S5P_GPIO_INT2_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x1c)
#define S5P_GPIO_INT3_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x20)
#define S5P_GPIO_INT4_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x24)
#define S5P_GPIO_INT5_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x28)
#define S5P_GPIO_INT6_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x2c)
#define S5P_GPIO_INT7_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x30)
#define S5P_GPIO_INT8_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x34)
#define S5P_GPIO_INT9_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x38)
#define S5P_GPIO_INT10_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x3c)
#define S5P_GPIO_INT11_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x40)
#define S5P_GPIO_INT12_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x44)
#define S5P_GPIO_INT13_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x48)
#define S5P_GPIO_INT14_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x4c)
#define S5P_GPIO_INT15_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x50)
#define S5P_GPIO_INT16_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x54)
#define S5P_GPIO_INT17_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x58)
#define S5P_GPIO_INT18_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x5c)
#define S5P_GPIO_INT19_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x60)
#define S5P_GPIO_INT20_FIXPRI			S5P_GPIO_INT_PRIO_REG(0x64)

/* GPIO H Bank Base */
#define S5P_GPIO_H0_BASE(x)		(S5P_GPIO_H_REG(0x0) + (x))
#define S5P_GPIO_H1_BASE(x)		(S5P_GPIO_H_REG(0x20) + (x))
#define S5P_GPIO_H2_BASE(x)		(S5P_GPIO_H_REG(0x40) + (x))
#define S5P_GPIO_H3_BASE(x)		(S5P_GPIO_H_REG(0x60) + (x))

#define S5P_GPIO_H0_CON			S5P_GPIO_H0_BASE(CON_OFFSET)
#define S5P_GPIO_H0_DAT			S5P_GPIO_H0_BASE(DAT_OFFSET)
#define S5P_GPIO_H0_PULL			S5P_GPIO_H0_BASE(PULL_OFFSET)
#define S5P_GPIO_H0_DRV			S5P_GPIO_H0_BASE(DRV_OFFSET)
#define S5P_GPIO_H0_PDNCON			S5P_GPIO_H0_BASE(PDNCON_OFFSET)
#define S5P_GPIO_H0_PDNPUL			S5P_GPIO_H0_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_H1_CON			S5P_GPIO_H1_BASE(CON_OFFSET)
#define S5P_GPIO_H1_DAT			S5P_GPIO_H1_BASE(DAT_OFFSET)
#define S5P_GPIO_H1_PULL			S5P_GPIO_H1_BASE(PULL_OFFSET)
#define S5P_GPIO_H1_DRV			S5P_GPIO_H1_BASE(DRV_OFFSET)
#define S5P_GPIO_H1_PDNCON			S5P_GPIO_H1_BASE(PDNCON_OFFSET)
#define S5P_GPIO_H1_PDNPUL			S5P_GPIO_H1_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_H2_CON			S5P_GPIO_H2_BASE(CON_OFFSET)
#define S5P_GPIO_H2_DAT			S5P_GPIO_H2_BASE(DAT_OFFSET)
#define S5P_GPIO_H2_PULL			S5P_GPIO_H2_BASE(PULL_OFFSET)
#define S5P_GPIO_H2_DRV			S5P_GPIO_H2_BASE(DRV_OFFSET)
#define S5P_GPIO_H2_PDNCON			S5P_GPIO_H2_BASE(PDNCON_OFFSET)
#define S5P_GPIO_H2_PDNPUL			S5P_GPIO_H2_BASE(PDNPULL_OFFSET)

#define S5P_GPIO_H3_CON			S5P_GPIO_H3_BASE(CON_OFFSET)
#define S5P_GPIO_H3_DAT			S5P_GPIO_H3_BASE(DAT_OFFSET)
#define S5P_GPIO_H3_PULL			S5P_GPIO_H3_BASE(PULL_OFFSET)
#define S5P_GPIO_H3_DRV			S5P_GPIO_H3_BASE(DRV_OFFSET)
#define S5P_GPIO_H3_PDNCON			S5P_GPIO_H3_BASE(PDNCON_OFFSET)
#define S5P_GPIO_H3_PDNPUL			S5P_GPIO_H3_BASE(PDNPULL_OFFSET)

/* GPIO Wakeup Interrupt Configuration */
#define S5P_GPIO_WAKEUP_INT0_CON	S5P_WAKEUP_INT_CON(0x00)
#define S5P_GPIO_WAKEUP_INT1_CON	S5P_WAKEUP_INT_CON(0x04)
#define S5P_GPIO_WAKEUP_INT2_CON	S5P_WAKEUP_INT_CON(0x08)
#define S5P_GPIO_WAKEUP_INT3_CON	S5P_WAKEUP_INT_CON(0x0c)

/* GPIO Wakeup Interrupt Filter Configuration */
#define S5P_GPIO_WAKEUP_FLTINT0_CON0	S5P_WAKEUP_FLTINT_CON(0x00)
#define S5P_GPIO_WAKEUP_FLTINT0_CON1	S5P_WAKEUP_FLTINT_CON(0x04)
#define S5P_GPIO_WAKEUP_FLTINT1_CON0	S5P_WAKEUP_FLTINT_CON(0x08)
#define S5P_GPIO_WAKEUP_FLTINT1_CON1	S5P_WAKEUP_FLTINT_CON(0x0c)
#define S5P_GPIO_WAKEUP_FLTINT2_CON0	S5P_WAKEUP_FLTINT_CON(0x10)
#define S5P_GPIO_WAKEUP_FLTINT2_CON1	S5P_WAKEUP_FLTINT_CON(0x14)
#define S5P_GPIO_WAKEUP_FLTINT3_CON0	S5P_WAKEUP_FLTINT_CON(0x18)
#define S5P_GPIO_WAKEUP_FLTINT3_CON1	S5P_WAKEUP_FLTINT_CON(0x1c)

/* GPIO Wakeup Interrupt Mask */
#define S5P_GPIO_WAKEUP_INT0_MASK	S5P_WAKEUP_INT_MASK(0x00)
#define S5P_GPIO_WAKEUP_INT1_MASK	S5P_WAKEUP_INT_MASK(0x04)
#define S5P_GPIO_WAKEUP_INT2_MASK	S5P_WAKEUP_INT_MASK(0x08)
#define S5P_GPIO_WAKEUP_INT3_MASK	S5P_WAKEUP_INT_MASK(0x0c)

/* GPIO Wakeup Interrupt Pend */
#define S5P_GPIO_WAKEUP_INT0_PEND	S5P_WAKEUP_INT_PEND(0x00)
#define S5P_GPIO_WAKEUP_INT1_PEND	S5P_WAKEUP_INT_PEND(0x04)
#define S5P_GPIO_WAKEUP_INT2_PEND	S5P_WAKEUP_INT_PEND(0x08)
#define S5P_GPIO_WAKEUP_INT3_PEND	S5P_WAKEUP_INT_PEND(0x0c)


/* 
 * Vector Interrupt Controller
 * : VIC0, VIC1, VIC2
 */

/* VIC0 */
#define S5P_VIC0_BASE(x)			(S5P_PA_VIC0 + (x))
#define S5P_VIC0_VECT_ADDR_BASE(x)	(S5P_PA_VIC0 + 0x100 + (x))
#define S5P_VIC0_VECT_PRIO_BASE(x)	(S5P_PA_VIC0 + 0x200 + (x))
#define S5P_VIC0_ADDRESS_BASE(x)	(S5P_PA_VIC0 + 0xf00 + (x))

#define IRQSTATUS_OFFSET		0x0		/* IRQ Status Register */
#define FIQSTATUS_OFFSET		0x4		/* FIQ Status Register */
#define RAWINTR_OFFSET			0x8		/* Raw Interrupt Status Register */
#define INTSELECT_OFFSET		0xc		/* Interrupt Select Register */
#define INTENABLE_OFFSET		0x10	/* Interrupt Enable Register */
#define INTENCLEAR_OFFSET		0x14	/* Interrupt Enable Clear Register */
#define SOFTINT_OFFSET			0x18	/* Software Interrupt Register */
#define SOFTINTCLEAR_OFFSET		0x1c	/* Software Interrupt Clear Register */
#define PROTECTION_OFFSET		0x20	/* Protection Enable Register */
#define SWPRIORITYMASK_OFFSET	0x24	/* Software Priority Mask Register */
#define PRIORITYDAISY_OFFSET	0x28	/* Vector Priority Register for Daisy Chain */

#define S5P_VIC0IRQSTATUS		S5P_VIC0_BASE(IRQSTATUS_OFFSET)
#define S5P_VIC0FIQSTATUS		S5P_VIC0_BASE(FIQSTATUS_OFFSET)
#define S5P_VIC0RAWINTR			S5P_VIC0_BASE(RAWINTR_OFFSET)
#define S5P_VIC0INTSELECT		S5P_VIC0_BASE(INTSELECT_OFFSET)
#define S5P_VIC0INTENABLE		S5P_VIC0_BASE(INTENABLE_OFFSET)
#define S5P_VIC0INTENCLEAR		S5P_VIC0_BASE(INTENCLEAR_OFFSET)
#define S5P_VIC0SOFTINT			S5P_VIC0_BASE(SOFTINT_OFFSET)
#define S5P_VIC0SOFTINTCLEAR	S5P_VIC0_BASE(SOFTINTCLEAR_OFFSET)
#define S5P_VIC0PROTECTION		S5P_VIC0_BASE(PROTECTION_OFFSET)
#define S5P_VIC0SWPRIORITYMASK	S5P_VIC0_BASE(SWPRIORITYMASK_OFFSET)
#define S5P_VIC0PRIORITYDAISY	S5P_VIC0_BASE(PRIORITYDAISY_OFFSET)

#define S5P_VIC0VECTADDR0		S5P_VIC0_VECT_ADDR_BASE(0x00)
#define S5P_VIC0VECTADDR1		S5P_VIC0_VECT_ADDR_BASE(0x04)
#define S5P_VIC0VECTADDR2		S5P_VIC0_VECT_ADDR_BASE(0x08)
#define S5P_VIC0VECTADDR3		S5P_VIC0_VECT_ADDR_BASE(0x0c)
#define S5P_VIC0VECTADDR4		S5P_VIC0_VECT_ADDR_BASE(0x10)
#define S5P_VIC0VECTADDR5		S5P_VIC0_VECT_ADDR_BASE(0x14)
#define S5P_VIC0VECTADDR6		S5P_VIC0_VECT_ADDR_BASE(0x18)
#define S5P_VIC0VECTADDR7		S5P_VIC0_VECT_ADDR_BASE(0x1c)
#define S5P_VIC0VECTADDR8		S5P_VIC0_VECT_ADDR_BASE(0x20)
#define S5P_VIC0VECTADDR9		S5P_VIC0_VECT_ADDR_BASE(0x24)
#define S5P_VIC0VECTADDR10		S5P_VIC0_VECT_ADDR_BASE(0x28)
#define S5P_VIC0VECTADDR11		S5P_VIC0_VECT_ADDR_BASE(0x2c)
#define S5P_VIC0VECTADDR12		S5P_VIC0_VECT_ADDR_BASE(0x30)
#define S5P_VIC0VECTADDR13		S5P_VIC0_VECT_ADDR_BASE(0x34)
#define S5P_VIC0VECTADDR14		S5P_VIC0_VECT_ADDR_BASE(0x38)
#define S5P_VIC0VECTADDR15		S5P_VIC0_VECT_ADDR_BASE(0x3c)
#define S5P_VIC0VECTADDR16		S5P_VIC0_VECT_ADDR_BASE(0x40)
#define S5P_VIC0VECTADDR17		S5P_VIC0_VECT_ADDR_BASE(0x44)
#define S5P_VIC0VECTADDR18		S5P_VIC0_VECT_ADDR_BASE(0x48)
#define S5P_VIC0VECTADDR19		S5P_VIC0_VECT_ADDR_BASE(0x4c)
#define S5P_VIC0VECTADDR20		S5P_VIC0_VECT_ADDR_BASE(0x50)
#define S5P_VIC0VECTADDR21		S5P_VIC0_VECT_ADDR_BASE(0x54)
#define S5P_VIC0VECTADDR22		S5P_VIC0_VECT_ADDR_BASE(0x58)
#define S5P_VIC0VECTADDR23		S5P_VIC0_VECT_ADDR_BASE(0x5c)
#define S5P_VIC0VECTADDR24		S5P_VIC0_VECT_ADDR_BASE(0x60)
#define S5P_VIC0VECTADDR25		S5P_VIC0_VECT_ADDR_BASE(0x64)
#define S5P_VIC0VECTADDR26		S5P_VIC0_VECT_ADDR_BASE(0x68)
#define S5P_VIC0VECTADDR27		S5P_VIC0_VECT_ADDR_BASE(0x6c)
#define S5P_VIC0VECTADDR28		S5P_VIC0_VECT_ADDR_BASE(0x70)
#define S5P_VIC0VECTADDR29		S5P_VIC0_VECT_ADDR_BASE(0x74)
#define S5P_VIC0VECTADDR30		S5P_VIC0_VECT_ADDR_BASE(0x78)
#define S5P_VIC0VECTADDR31		S5P_VIC0_VECT_ADDR_BASE(0x7c)

#define S5P_VIC0VECTPRIO0		S5P_VIC0_VECT_PRIO_BASE(0x00)
#define S5P_VIC0VECTPRIO1		S5P_VIC0_VECT_PRIO_BASE(0x04)
#define S5P_VIC0VECTPRIO2		S5P_VIC0_VECT_PRIO_BASE(0x08)
#define S5P_VIC0VECTPRIO3		S5P_VIC0_VECT_PRIO_BASE(0x0c)
#define S5P_VIC0VECTPRIO4		S5P_VIC0_VECT_PRIO_BASE(0x10)
#define S5P_VIC0VECTPRIO5		S5P_VIC0_VECT_PRIO_BASE(0x14)
#define S5P_VIC0VECTPRIO6		S5P_VIC0_VECT_PRIO_BASE(0x18)
#define S5P_VIC0VECTPRIO7		S5P_VIC0_VECT_PRIO_BASE(0x1c)
#define S5P_VIC0VECTPRIO8		S5P_VIC0_VECT_PRIO_BASE(0x20)
#define S5P_VIC0VECTPRIO9		S5P_VIC0_VECT_PRIO_BASE(0x24)
#define S5P_VIC0VECTPRIO10		S5P_VIC0_VECT_PRIO_BASE(0x28)
#define S5P_VIC0VECTPRIO11		S5P_VIC0_VECT_PRIO_BASE(0x2c)
#define S5P_VIC0VECTPRIO12		S5P_VIC0_VECT_PRIO_BASE(0x30)
#define S5P_VIC0VECTPRIO13		S5P_VIC0_VECT_PRIO_BASE(0x34)
#define S5P_VIC0VECTPRIO14		S5P_VIC0_VECT_PRIO_BASE(0x38)
#define S5P_VIC0VECTPRIO15		S5P_VIC0_VECT_PRIO_BASE(0x3c)
#define S5P_VIC0VECTPRIO16		S5P_VIC0_VECT_PRIO_BASE(0x40)
#define S5P_VIC0VECTPRIO17		S5P_VIC0_VECT_PRIO_BASE(0x44)
#define S5P_VIC0VECTPRIO18		S5P_VIC0_VECT_PRIO_BASE(0x48)
#define S5P_VIC0VECTPRIO19		S5P_VIC0_VECT_PRIO_BASE(0x4c)
#define S5P_VIC0VECTPRIO20		S5P_VIC0_VECT_PRIO_BASE(0x50)
#define S5P_VIC0VECTPRIO21		S5P_VIC0_VECT_PRIO_BASE(0x54)
#define S5P_VIC0VECTPRIO22		S5P_VIC0_VECT_PRIO_BASE(0x58)
#define S5P_VIC0VECTPRIO23		S5P_VIC0_VECT_PRIO_BASE(0x5c)
#define S5P_VIC0VECTPRIO24		S5P_VIC0_VECT_PRIO_BASE(0x60)
#define S5P_VIC0VECTPRIO25		S5P_VIC0_VECT_PRIO_BASE(0x64)
#define S5P_VIC0VECTPRIO26		S5P_VIC0_VECT_PRIO_BASE(0x68)
#define S5P_VIC0VECTPRIO27		S5P_VIC0_VECT_PRIO_BASE(0x6c)
#define S5P_VIC0VECTPRIO28		S5P_VIC0_VECT_PRIO_BASE(0x70)
#define S5P_VIC0VECTPRIO29		S5P_VIC0_VECT_PRIO_BASE(0x74)
#define S5P_VIC0VECTPRIO30		S5P_VIC0_VECT_PRIO_BASE(0x78)
#define S5P_VIC0VECTPRIO31		S5P_VIC0_VECT_PRIO_BASE(0x7c)

#define S5P_VIC0ADDRESS			S5P_VIC0_ADDRESS_BASE(0x0)
#define S5P_VIC0PERIPHID0		S5P_VIC0_ADDRESS_BASE(0xe0)
#define S5P_VIC0PERIPHID1		S5P_VIC0_ADDRESS_BASE(0xe4)
#define S5P_VIC0PERIPHID2		S5P_VIC0_ADDRESS_BASE(0xe8)
#define S5P_VIC0PERIPHID3		S5P_VIC0_ADDRESS_BASE(0xec)
#define S5P_VIC0PCELLID0		S5P_VIC0_ADDRESS_BASE(0xf0)
#define S5P_VIC0PCELLID1		S5P_VIC0_ADDRESS_BASE(0xf4)
#define S5P_VIC0PCELLID2		S5P_VIC0_ADDRESS_BASE(0xf8)
#define S5P_VIC0PCELLID3		S5P_VIC0_ADDRESS_BASE(0xfc)


/* VIC1 */
#define S5P_VIC1_BASE(x)			(S5P_PA_VIC1 + (x))
#define S5P_VIC1_VECT_ADDR_BASE(x)	(S5P_PA_VIC1 + 0x100 + (x))
#define S5P_VIC1_VECT_PRIO_BASE(x)	(S5P_PA_VIC1 + 0x200 + (x))
#define S5P_VIC1_ADDRESS_BASE(x)	(S5P_PA_VIC1 + 0xf00 + (x))

#define IRQSTATUS_OFFSET		0x0		/* IRQ Status Register */
#define FIQSTATUS_OFFSET		0x4		/* FIQ Status Register */
#define RAWINTR_OFFSET			0x8		/* Raw Interrupt Status Register */
#define INTSELECT_OFFSET		0xc		/* Interrupt Select Register */
#define INTENABLE_OFFSET		0x10	/* Interrupt Enable Register */
#define INTENCLEAR_OFFSET		0x14	/* Interrupt Enable Clear Register */
#define SOFTINT_OFFSET			0x18	/* Software Interrupt Register */
#define SOFTINTCLEAR_OFFSET		0x1c	/* Software Interrupt Clear Register */
#define PROTECTION_OFFSET		0x20	/* Protection Enable Register */
#define SWPRIORITYMASK_OFFSET	0x24	/* Software Priority Mask Register */
#define PRIORITYDAISY_OFFSET	0x28	/* Vector Priority Register for Daisy Chain */

#define S5P_VIC1IRQSTATUS		S5P_VIC1_BASE(IRQSTATUS_OFFSET)
#define S5P_VIC1FIQSTATUS		S5P_VIC1_BASE(FIQSTATUS_OFFSET)
#define S5P_VIC1RAWINTR			S5P_VIC1_BASE(RAWINTR_OFFSET)
#define S5P_VIC1INTSELECT		S5P_VIC1_BASE(INTSELECT_OFFSET)
#define S5P_VIC1INTENABLE		S5P_VIC1_BASE(INTENABLE_OFFSET)
#define S5P_VIC1INTENCLEAR		S5P_VIC1_BASE(INTENCLEAR_OFFSET)
#define S5P_VIC1SOFTINT			S5P_VIC1_BASE(SOFTINT_OFFSET)
#define S5P_VIC1SOFTINTCLEAR	S5P_VIC1_BASE(SOFTINTCLEAR_OFFSET)
#define S5P_VIC1PROTECTION		S5P_VIC1_BASE(PROTECTION_OFFSET)
#define S5P_VIC1SWPRIORITYMASK	S5P_VIC1_BASE(SWPRIORITYMASK_OFFSET)
#define S5P_VIC1PRIORITYDAISY	S5P_VIC1_BASE(PRIORITYDAISY_OFFSET)

#define S5P_VIC1VECTADDR0		S5P_VIC1_VECT_ADDR_BASE(0x00)
#define S5P_VIC1VECTADDR1		S5P_VIC1_VECT_ADDR_BASE(0x04)
#define S5P_VIC1VECTADDR2		S5P_VIC1_VECT_ADDR_BASE(0x08)
#define S5P_VIC1VECTADDR3		S5P_VIC1_VECT_ADDR_BASE(0x0c)
#define S5P_VIC1VECTADDR4		S5P_VIC1_VECT_ADDR_BASE(0x10)
#define S5P_VIC1VECTADDR5		S5P_VIC1_VECT_ADDR_BASE(0x14)
#define S5P_VIC1VECTADDR6		S5P_VIC1_VECT_ADDR_BASE(0x18)
#define S5P_VIC1VECTADDR7		S5P_VIC1_VECT_ADDR_BASE(0x1c)
#define S5P_VIC1VECTADDR8		S5P_VIC1_VECT_ADDR_BASE(0x20)
#define S5P_VIC1VECTADDR9		S5P_VIC1_VECT_ADDR_BASE(0x24)
#define S5P_VIC1VECTADDR10		S5P_VIC1_VECT_ADDR_BASE(0x28)
#define S5P_VIC1VECTADDR11		S5P_VIC1_VECT_ADDR_BASE(0x2c)
#define S5P_VIC1VECTADDR12		S5P_VIC1_VECT_ADDR_BASE(0x30)
#define S5P_VIC1VECTADDR13		S5P_VIC1_VECT_ADDR_BASE(0x34)
#define S5P_VIC1VECTADDR14		S5P_VIC1_VECT_ADDR_BASE(0x38)
#define S5P_VIC1VECTADDR15		S5P_VIC1_VECT_ADDR_BASE(0x3c)
#define S5P_VIC1VECTADDR16		S5P_VIC1_VECT_ADDR_BASE(0x40)
#define S5P_VIC1VECTADDR17		S5P_VIC1_VECT_ADDR_BASE(0x44)
#define S5P_VIC1VECTADDR18		S5P_VIC1_VECT_ADDR_BASE(0x48)
#define S5P_VIC1VECTADDR19		S5P_VIC1_VECT_ADDR_BASE(0x4c)
#define S5P_VIC1VECTADDR20		S5P_VIC1_VECT_ADDR_BASE(0x50)
#define S5P_VIC1VECTADDR21		S5P_VIC1_VECT_ADDR_BASE(0x54)
#define S5P_VIC1VECTADDR22		S5P_VIC1_VECT_ADDR_BASE(0x58)
#define S5P_VIC1VECTADDR23		S5P_VIC1_VECT_ADDR_BASE(0x5c)
#define S5P_VIC1VECTADDR24		S5P_VIC1_VECT_ADDR_BASE(0x60)
#define S5P_VIC1VECTADDR25		S5P_VIC1_VECT_ADDR_BASE(0x64)
#define S5P_VIC1VECTADDR26		S5P_VIC1_VECT_ADDR_BASE(0x68)
#define S5P_VIC1VECTADDR27		S5P_VIC1_VECT_ADDR_BASE(0x6c)
#define S5P_VIC1VECTADDR28		S5P_VIC1_VECT_ADDR_BASE(0x70)
#define S5P_VIC1VECTADDR29		S5P_VIC1_VECT_ADDR_BASE(0x74)
#define S5P_VIC1VECTADDR30		S5P_VIC1_VECT_ADDR_BASE(0x78)
#define S5P_VIC1VECTADDR31		S5P_VIC1_VECT_ADDR_BASE(0x7c)

#define S5P_VIC1VECTPRIO0		S5P_VIC1_VECT_PRIO_BASE(0x00)
#define S5P_VIC1VECTPRIO1		S5P_VIC1_VECT_PRIO_BASE(0x04)
#define S5P_VIC1VECTPRIO2		S5P_VIC1_VECT_PRIO_BASE(0x08)
#define S5P_VIC1VECTPRIO3		S5P_VIC1_VECT_PRIO_BASE(0x0c)
#define S5P_VIC1VECTPRIO4		S5P_VIC1_VECT_PRIO_BASE(0x10)
#define S5P_VIC1VECTPRIO5		S5P_VIC1_VECT_PRIO_BASE(0x14)
#define S5P_VIC1VECTPRIO6		S5P_VIC1_VECT_PRIO_BASE(0x18)
#define S5P_VIC1VECTPRIO7		S5P_VIC1_VECT_PRIO_BASE(0x1c)
#define S5P_VIC1VECTPRIO8		S5P_VIC1_VECT_PRIO_BASE(0x20)
#define S5P_VIC1VECTPRIO9		S5P_VIC1_VECT_PRIO_BASE(0x24)
#define S5P_VIC1VECTPRIO10		S5P_VIC1_VECT_PRIO_BASE(0x28)
#define S5P_VIC1VECTPRIO11		S5P_VIC1_VECT_PRIO_BASE(0x2c)
#define S5P_VIC1VECTPRIO12		S5P_VIC1_VECT_PRIO_BASE(0x30)
#define S5P_VIC1VECTPRIO13		S5P_VIC1_VECT_PRIO_BASE(0x34)
#define S5P_VIC1VECTPRIO14		S5P_VIC1_VECT_PRIO_BASE(0x38)
#define S5P_VIC1VECTPRIO15		S5P_VIC1_VECT_PRIO_BASE(0x3c)
#define S5P_VIC1VECTPRIO16		S5P_VIC1_VECT_PRIO_BASE(0x40)
#define S5P_VIC1VECTPRIO17		S5P_VIC1_VECT_PRIO_BASE(0x44)
#define S5P_VIC1VECTPRIO18		S5P_VIC1_VECT_PRIO_BASE(0x48)
#define S5P_VIC1VECTPRIO19		S5P_VIC1_VECT_PRIO_BASE(0x4c)
#define S5P_VIC1VECTPRIO20		S5P_VIC1_VECT_PRIO_BASE(0x50)
#define S5P_VIC1VECTPRIO21		S5P_VIC1_VECT_PRIO_BASE(0x54)
#define S5P_VIC1VECTPRIO22		S5P_VIC1_VECT_PRIO_BASE(0x58)
#define S5P_VIC1VECTPRIO23		S5P_VIC1_VECT_PRIO_BASE(0x5c)
#define S5P_VIC1VECTPRIO24		S5P_VIC1_VECT_PRIO_BASE(0x60)
#define S5P_VIC1VECTPRIO25		S5P_VIC1_VECT_PRIO_BASE(0x64)
#define S5P_VIC1VECTPRIO26		S5P_VIC1_VECT_PRIO_BASE(0x68)
#define S5P_VIC1VECTPRIO27		S5P_VIC1_VECT_PRIO_BASE(0x6c)
#define S5P_VIC1VECTPRIO28		S5P_VIC1_VECT_PRIO_BASE(0x70)
#define S5P_VIC1VECTPRIO29		S5P_VIC1_VECT_PRIO_BASE(0x74)
#define S5P_VIC1VECTPRIO30		S5P_VIC1_VECT_PRIO_BASE(0x78)
#define S5P_VIC1VECTPRIO31		S5P_VIC1_VECT_PRIO_BASE(0x7c)

#define S5P_VIC1ADDRESS			S5P_VIC1_ADDRESS_BASE(0x0)
#define S5P_VIC1PERIPHID0		S5P_VIC1_ADDRESS_BASE(0xe0)
#define S5P_VIC1PERIPHID1		S5P_VIC1_ADDRESS_BASE(0xe4)
#define S5P_VIC1PERIPHID2		S5P_VIC1_ADDRESS_BASE(0xe8)
#define S5P_VIC1PERIPHID3		S5P_VIC1_ADDRESS_BASE(0xec)
#define S5P_VIC1PCELLID0		S5P_VIC1_ADDRESS_BASE(0xf0)
#define S5P_VIC1PCELLID1		S5P_VIC1_ADDRESS_BASE(0xf4)
#define S5P_VIC1PCELLID2		S5P_VIC1_ADDRESS_BASE(0xf8)
#define S5P_VIC1PCELLID3		S5P_VIC1_ADDRESS_BASE(0xfc)


/* VIC2 */
#define S5P_VIC2_BASE(x)			(S5P_PA_VIC2 + (x))
#define S5P_VIC2_VECT_ADDR_BASE(x)	(S5P_PA_VIC2 + 0x100 + (x))
#define S5P_VIC2_VECT_PRIO_BASE(x)	(S5P_PA_VIC2 + 0x200 + (x))
#define S5P_VIC2_ADDRESS_BASE(x)	(S5P_PA_VIC2 + 0xf00 + (x))

#define IRQSTATUS_OFFSET		0x0		/* IRQ Status Register */
#define FIQSTATUS_OFFSET		0x4		/* FIQ Status Register */
#define RAWINTR_OFFSET			0x8		/* Raw Interrupt Status Register */
#define INTSELECT_OFFSET		0xc		/* Interrupt Select Register */
#define INTENABLE_OFFSET		0x10	/* Interrupt Enable Register */
#define INTENCLEAR_OFFSET		0x14	/* Interrupt Enable Clear Register */
#define SOFTINT_OFFSET			0x18	/* Software Interrupt Register */
#define SOFTINTCLEAR_OFFSET		0x1c	/* Software Interrupt Clear Register */
#define PROTECTION_OFFSET		0x20	/* Protection Enable Register */
#define SWPRIORITYMASK_OFFSET	0x24	/* Software Priority Mask Register */
#define PRIORITYDAISY_OFFSET	0x28	/* Vector Priority Register for Daisy Chain */

#define S5P_VIC2IRQSTATUS		S5P_VIC2_BASE(IRQSTATUS_OFFSET)
#define S5P_VIC2FIQSTATUS		S5P_VIC2_BASE(FIQSTATUS_OFFSET)
#define S5P_VIC2RAWINTR			S5P_VIC2_BASE(RAWINTR_OFFSET)
#define S5P_VIC2INTSELECT		S5P_VIC2_BASE(INTSELECT_OFFSET)
#define S5P_VIC2INTENABLE		S5P_VIC2_BASE(INTENABLE_OFFSET)
#define S5P_VIC2INTENCLEAR		S5P_VIC2_BASE(INTENCLEAR_OFFSET)
#define S5P_VIC2SOFTINT			S5P_VIC2_BASE(SOFTINT_OFFSET)
#define S5P_VIC2SOFTINTCLEAR	S5P_VIC2_BASE(SOFTINTCLEAR_OFFSET)
#define S5P_VIC2PROTECTION		S5P_VIC2_BASE(PROTECTION_OFFSET)
#define S5P_VIC2SWPRIORITYMASK	S5P_VIC2_BASE(SWPRIORITYMASK_OFFSET)
#define S5P_VIC2PRIORITYDAISY	S5P_VIC2_BASE(PRIORITYDAISY_OFFSET)

#define S5P_VIC2VECTADDR0		S5P_VIC2_VECT_ADDR_BASE(0x00)
#define S5P_VIC2VECTADDR1		S5P_VIC2_VECT_ADDR_BASE(0x04)
#define S5P_VIC2VECTADDR2		S5P_VIC2_VECT_ADDR_BASE(0x08)
#define S5P_VIC2VECTADDR3		S5P_VIC2_VECT_ADDR_BASE(0x0c)
#define S5P_VIC2VECTADDR4		S5P_VIC2_VECT_ADDR_BASE(0x10)
#define S5P_VIC2VECTADDR5		S5P_VIC2_VECT_ADDR_BASE(0x14)
#define S5P_VIC2VECTADDR6		S5P_VIC2_VECT_ADDR_BASE(0x18)
#define S5P_VIC2VECTADDR7		S5P_VIC2_VECT_ADDR_BASE(0x1c)
#define S5P_VIC2VECTADDR8		S5P_VIC2_VECT_ADDR_BASE(0x20)
#define S5P_VIC2VECTADDR9		S5P_VIC2_VECT_ADDR_BASE(0x24)
#define S5P_VIC2VECTADDR10		S5P_VIC2_VECT_ADDR_BASE(0x28)
#define S5P_VIC2VECTADDR11		S5P_VIC2_VECT_ADDR_BASE(0x2c)
#define S5P_VIC2VECTADDR12		S5P_VIC2_VECT_ADDR_BASE(0x30)
#define S5P_VIC2VECTADDR13		S5P_VIC2_VECT_ADDR_BASE(0x34)
#define S5P_VIC2VECTADDR14		S5P_VIC2_VECT_ADDR_BASE(0x38)
#define S5P_VIC2VECTADDR15		S5P_VIC2_VECT_ADDR_BASE(0x3c)
#define S5P_VIC2VECTADDR16		S5P_VIC2_VECT_ADDR_BASE(0x40)
#define S5P_VIC2VECTADDR17		S5P_VIC2_VECT_ADDR_BASE(0x44)
#define S5P_VIC2VECTADDR18		S5P_VIC2_VECT_ADDR_BASE(0x48)
#define S5P_VIC2VECTADDR19		S5P_VIC2_VECT_ADDR_BASE(0x4c)
#define S5P_VIC2VECTADDR20		S5P_VIC2_VECT_ADDR_BASE(0x50)
#define S5P_VIC2VECTADDR21		S5P_VIC2_VECT_ADDR_BASE(0x54)
#define S5P_VIC2VECTADDR22		S5P_VIC2_VECT_ADDR_BASE(0x58)
#define S5P_VIC2VECTADDR23		S5P_VIC2_VECT_ADDR_BASE(0x5c)
#define S5P_VIC2VECTADDR24		S5P_VIC2_VECT_ADDR_BASE(0x60)
#define S5P_VIC2VECTADDR25		S5P_VIC2_VECT_ADDR_BASE(0x64)
#define S5P_VIC2VECTADDR26		S5P_VIC2_VECT_ADDR_BASE(0x68)
#define S5P_VIC2VECTADDR27		S5P_VIC2_VECT_ADDR_BASE(0x6c)
#define S5P_VIC2VECTADDR28		S5P_VIC2_VECT_ADDR_BASE(0x70)
#define S5P_VIC2VECTADDR29		S5P_VIC2_VECT_ADDR_BASE(0x74)
#define S5P_VIC2VECTADDR30		S5P_VIC2_VECT_ADDR_BASE(0x78)
#define S5P_VIC2VECTADDR31		S5P_VIC2_VECT_ADDR_BASE(0x7c)

#define S5P_VIC2VECTPRIO0		S5P_VIC2_VECT_PRIO_BASE(0x00)
#define S5P_VIC2VECTPRIO1		S5P_VIC2_VECT_PRIO_BASE(0x04)
#define S5P_VIC2VECTPRIO2		S5P_VIC2_VECT_PRIO_BASE(0x08)
#define S5P_VIC2VECTPRIO3		S5P_VIC2_VECT_PRIO_BASE(0x0c)
#define S5P_VIC2VECTPRIO4		S5P_VIC2_VECT_PRIO_BASE(0x10)
#define S5P_VIC2VECTPRIO5		S5P_VIC2_VECT_PRIO_BASE(0x14)
#define S5P_VIC2VECTPRIO6		S5P_VIC2_VECT_PRIO_BASE(0x18)
#define S5P_VIC2VECTPRIO7		S5P_VIC2_VECT_PRIO_BASE(0x1c)
#define S5P_VIC2VECTPRIO8		S5P_VIC2_VECT_PRIO_BASE(0x20)
#define S5P_VIC2VECTPRIO9		S5P_VIC2_VECT_PRIO_BASE(0x24)
#define S5P_VIC2VECTPRIO10		S5P_VIC2_VECT_PRIO_BASE(0x28)
#define S5P_VIC2VECTPRIO11		S5P_VIC2_VECT_PRIO_BASE(0x2c)
#define S5P_VIC2VECTPRIO12		S5P_VIC2_VECT_PRIO_BASE(0x30)
#define S5P_VIC2VECTPRIO13		S5P_VIC2_VECT_PRIO_BASE(0x34)
#define S5P_VIC2VECTPRIO14		S5P_VIC2_VECT_PRIO_BASE(0x38)
#define S5P_VIC2VECTPRIO15		S5P_VIC2_VECT_PRIO_BASE(0x3c)
#define S5P_VIC2VECTPRIO16		S5P_VIC2_VECT_PRIO_BASE(0x40)
#define S5P_VIC2VECTPRIO17		S5P_VIC2_VECT_PRIO_BASE(0x44)
#define S5P_VIC2VECTPRIO18		S5P_VIC2_VECT_PRIO_BASE(0x48)
#define S5P_VIC2VECTPRIO19		S5P_VIC2_VECT_PRIO_BASE(0x4c)
#define S5P_VIC2VECTPRIO20		S5P_VIC2_VECT_PRIO_BASE(0x50)
#define S5P_VIC2VECTPRIO21		S5P_VIC2_VECT_PRIO_BASE(0x54)
#define S5P_VIC2VECTPRIO22		S5P_VIC2_VECT_PRIO_BASE(0x58)
#define S5P_VIC2VECTPRIO23		S5P_VIC2_VECT_PRIO_BASE(0x5c)
#define S5P_VIC2VECTPRIO24		S5P_VIC2_VECT_PRIO_BASE(0x60)
#define S5P_VIC2VECTPRIO25		S5P_VIC2_VECT_PRIO_BASE(0x64)
#define S5P_VIC2VECTPRIO26		S5P_VIC2_VECT_PRIO_BASE(0x68)
#define S5P_VIC2VECTPRIO27		S5P_VIC2_VECT_PRIO_BASE(0x6c)
#define S5P_VIC2VECTPRIO28		S5P_VIC2_VECT_PRIO_BASE(0x70)
#define S5P_VIC2VECTPRIO29		S5P_VIC2_VECT_PRIO_BASE(0x74)
#define S5P_VIC2VECTPRIO30		S5P_VIC2_VECT_PRIO_BASE(0x78)
#define S5P_VIC2VECTPRIO31		S5P_VIC2_VECT_PRIO_BASE(0x7c)

#define S5P_VIC2ADDRESS			S5P_VIC2_ADDRESS_BASE(0x0)
#define S5P_VIC2PERIPHID0		S5P_VIC2_ADDRESS_BASE(0xe0)
#define S5P_VIC2PERIPHID1		S5P_VIC2_ADDRESS_BASE(0xe4)
#define S5P_VIC2PERIPHID2		S5P_VIC2_ADDRESS_BASE(0xe8)
#define S5P_VIC2PERIPHID3		S5P_VIC2_ADDRESS_BASE(0xec)
#define S5P_VIC2PCELLID0		S5P_VIC2_ADDRESS_BASE(0xf0)
#define S5P_VIC2PCELLID1		S5P_VIC2_ADDRESS_BASE(0xf4)
#define S5P_VIC2PCELLID2		S5P_VIC2_ADDRESS_BASE(0xf8)
#define S5P_VIC2PCELLID3		S5P_VIC2_ADDRESS_BASE(0xfc)




/* 
 * TrustZone Interrupt Controller
 * : TZI0, TZI1, TZI2
 */
#define S5P_TZIC0_BASE(x)			(S5P_PA_TZIC0 + (x))
#define S5P_TZIC1_BASE(x)			(S5P_PA_TZIC1 + (x))
#define S5P_TZIC2_BASE(x)			(S5P_PA_TZIC2 + (x))

#define FIQSTATUS_OFFSET	(0x00)	/* FIQ Status Regieter */
#define RAWINTR_OFFSET		(0x04)	/* Raw Interrupt Status Register */
#define INTSELECT_OFFSET	(0x08)	/* Interrupt Select Register */
#define FIQENABLE_OFFSET	(0x0c)	/* FIQ Enable Register */
#define FIQENCLEAR_OFFSET	(0x10)	/* FIQ Enable Clear Register */
#define FIQBYPASS_OFFSET	(0x14)	/* FIQ Bypass Register */
#define FIQPROTECTION_OFFSET	(0x18)	/* Protection Register */
#define FIQLOCK_OFFSET			(0x1c)	/* Lock Enable Register */
#define FIQLOCKSTATUS_OFFSET	(0x20)	/* Lock Status Register */
#define PERIPHID0_OFFSET		(0xfe0)	/* Peripheral Identification Register */
#define PCELLID0_OFFSET		(0xff0)	/* PrimeCell Identification Register */

/* TZI0 */
#define S5P_TZIC0FIQSTATUS		S5P_TZIC0_BASE(FIQSTATUS_OFFSET)
#define S5P_TZIC0RAWINTR		S5P_TZIC0_BASE(RAQINTR_OFFSET)
#define S5P_TZIC0INTSELECT		S5P_TZIC0_BASE(INTSELECT_OFFSET)
#define S5P_TZIC0FIQENABLE		S5P_TZIC0_BASE(FIQENABLE_OFFSET)
#define S5P_TZIC0FIQENCLEAR		S5P_TZIC0_BASE(FIQENCLEAR_OFFSET)
#define S5P_TZIC0FIQBYPASS		S5P_TZIC0_BASE(FIQBYPASS_OFFSET)
#define S5P_TZIC0FIQPROTECTION	S5P_TZIC0_BASE(FIQPROTECTION_OFFSET)
#define S5P_TZIC0FIQLOCK		S5P_TZIC0_BASE(FIQLOCKSTATUS_OFFSET)
#define S5P_TZIC0FIQLOCKSTATUS	S5P_TZIC0_BASE(PCELLID0_OFFSET)

#define S5P_TZIC0PERIPHID0		S5P_TZIC0_BASE(PERIPHID0_OFFSET + 0x0)
#define S5P_TZIC0PERIPHID1		S5P_TZIC0_BASE(PERIPHID0_OFFSET + 0x4)
#define S5P_TZIC0PERIPHID2		S5P_TZIC0_BASE(PERIPHID0_OFFSET + 0x8)
#define S5P_TZIC0PERIPHID3		S5P_TZIC0_BASE(PERIPHID0_OFFSET + 0xc)

#define S5P_TZIC0PCELLID0		S5P_TZIC0_BASE(PCELLID0_OFFSET + 0x0)
#define S5P_TZIC0PCELLID1		S5P_TZIC0_BASE(PCELLID1_OFFSET + 0x0)
#define S5P_TZIC0PCELLID2		S5P_TZIC0_BASE(PCELLID2_OFFSET + 0x0)
#define S5P_TZIC0PCELLID3		S5P_TZIC0_BASE(PCELLID3_OFFSET + 0x0)

/* TZI1 */
#define S5P_TZIC1FIQSTATUS		S5P_TZIC1_BASE(FIQSTATUS_OFFSET)
#define S5P_TZIC1RAWINTR		S5P_TZIC1_BASE(RAQINTR_OFFSET)
#define S5P_TZIC1INTSELECT		S5P_TZIC1_BASE(INTSELECT_OFFSET)
#define S5P_TZIC1FIQENABLE		S5P_TZIC1_BASE(FIQENABLE_OFFSET)
#define S5P_TZIC1FIQENCLEAR		S5P_TZIC1_BASE(FIQENCLEAR_OFFSET)
#define S5P_TZIC1FIQBYPASS		S5P_TZIC1_BASE(FIQBYPASS_OFFSET)
#define S5P_TZIC1FIQPROTECTION	S5P_TZIC1_BASE(FIQPROTECTION_OFFSET)
#define S5P_TZIC1FIQLOCK		S5P_TZIC1_BASE(FIQLOCKSTATUS_OFFSET)
#define S5P_TZIC1FIQLOCKSTATUS	S5P_TZIC1_BASE(PCELLID0_OFFSET)

#define S5P_TZIC1PERIPHID0		S5P_TZIC1_BASE(PERIPHID0_OFFSET + 0x0)
#define S5P_TZIC1PERIPHID1		S5P_TZIC1_BASE(PERIPHID0_OFFSET + 0x4)
#define S5P_TZIC1PERIPHID2		S5P_TZIC1_BASE(PERIPHID0_OFFSET + 0x8)
#define S5P_TZIC1PERIPHID3		S5P_TZIC1_BASE(PERIPHID0_OFFSET + 0xc)

#define S5P_TZIC1PCELLID0		S5P_TZIC1_BASE(PCELLID0_OFFSET + 0x0)
#define S5P_TZIC1PCELLID1		S5P_TZIC1_BASE(PCELLID1_OFFSET + 0x0)
#define S5P_TZIC1PCELLID2		S5P_TZIC1_BASE(PCELLID2_OFFSET + 0x0)
#define S5P_TZIC1PCELLID3		S5P_TZIC1_BASE(PCELLID3_OFFSET + 0x0)

/* TZI2 */
#define S5P_TZIC2FIQSTATUS		S5P_TZIC2_BASE(FIQSTATUS_OFFSET)
#define S5P_TZIC2RAWINTR		S5P_TZIC2_BASE(RAQINTR_OFFSET)
#define S5P_TZIC2INTSELECT		S5P_TZIC2_BASE(INTSELECT_OFFSET)
#define S5P_TZIC2FIQENABLE		S5P_TZIC2_BASE(FIQENABLE_OFFSET)
#define S5P_TZIC2FIQENCLEAR		S5P_TZIC2_BASE(FIQENCLEAR_OFFSET)
#define S5P_TZIC2FIQBYPASS		S5P_TZIC2_BASE(FIQBYPASS_OFFSET)
#define S5P_TZIC2FIQPROTECTION	S5P_TZIC2_BASE(FIQPROTECTION_OFFSET)
#define S5P_TZIC2FIQLOCK		S5P_TZIC2_BASE(FIQLOCKSTATUS_OFFSET)
#define S5P_TZIC2FIQLOCKSTATUS	S5P_TZIC2_BASE(PCELLID0_OFFSET)

#define S5P_TZIC2PERIPHID0		S5P_TZIC2_BASE(PERIPHID0_OFFSET + 0x0)
#define S5P_TZIC2PERIPHID1		S5P_TZIC2_BASE(PERIPHID0_OFFSET + 0x4)
#define S5P_TZIC2PERIPHID2		S5P_TZIC2_BASE(PERIPHID0_OFFSET + 0x8)
#define S5P_TZIC2PERIPHID3		S5P_TZIC2_BASE(PERIPHID0_OFFSET + 0xc)

#define S5P_TZIC2PCELLID0		S5P_TZIC2_BASE(PCELLID0_OFFSET + 0x0)
#define S5P_TZIC2PCELLID1		S5P_TZIC2_BASE(PCELLID1_OFFSET + 0x0)
#define S5P_TZIC2PCELLID2		S5P_TZIC2_BASE(PCELLID2_OFFSET + 0x0)
#define S5P_TZIC2PCELLID3		S5P_TZIC2_BASE(PCELLID3_OFFSET + 0x0)



/*
 * Memory : SDRAM, SROM, OneNand
 */

/* DRAM Memory Controller */
#define S5P_DMC_BASE(x)		(S5P_PA_DMC + (x))

#define CONCONTROL_OFFSET	0x0		/* Controller Control Register */
#define MEMCONTROL_OFFSET	0x04	/* Memory Control Register */
#define MEMCONFIG0_OFFSET	0x08	/* Memory Chip0 Configuration Register */
#define MEMCONFIG1_OFFSET	0x0c	/* Memory Chip1 Configuration Register */
#define DIRECTCMD_OFFSET	0x10	/* Memory Direct Command Register */
#define PRECHCONFIG_OFFSET	0x14	/* Precharge Policy Configuration Register */
#define PHYCONTROL0_OFFSET	0x18	/* PHY Control0 Register */
#define PHYCONTROL1_OFFSET	0x1c	/* PHY Control1 Register */
#define PHYCONTROL2_OFFSET	0x20	/* PHY Control2 Register */
#define PWRDNCONFIG_OFFSET	0x28	/* Dynamic Power Down Configuration Register */
#define TIMINGAREF_OFFSET	0x30	/* AC Timing Register for SDRAM Auto Refresh */
#define TIMINGROW_OFFSET	0x34	/* AC Timing Register for SDRAM Row */
#define TIMINGDATA_OFFSET	0x38	/* AC Timing Register for SDRAM Data */
#define TIMINGPOWER_OFFSET	0x3c	/* AC Timing Register for Power Mode of SDRAM */
#define PHYSTATUS0_OFFSET	0x40	/* PHY Status Register 0 */
#define PHYSTATUS1_OFFSET	0x44	/* PHY Status Register 1 */
#define CHIP0STATUS_OFFSET	0x48	/* Memory Chip0 Status Register */
#define CHIP1STATUS_OFFSET	0x4c	/* Memory Chip1 Status Register */
#define AREFSTATUS_OFFSET	0x50	/* Counter status Register for Auto Refresh */
#define MRSTATUS_OFFSET		0x54	/* Memory Mode Registers Status Register */
#define PHYTEST0_OFFSET		0x58	/* PHY Test Register 0 */
#define PHYTEST1_OFFSET		0x5c	/* PHY Test Register 1 */
#define QOSCONTROL0_OFFSET	0x60	/* Quality of Service Control Register 0 */
#define QOSCONFIG0_OFFSET	0x64	/* Quality of Service Configuration Register 0 */
#define QOSCONTROL1_OFFSET	0x68
#define QOSCONFIG1_OFFSET	0x6c
#define QOSCONTROL2_OFFSET	0x70
#define QOSCONFIG2_OFFSET	0x74
#define QOSCONTROL3_OFFSET	0x78
#define QOSCONFIG3_OFFSET	0x7c
#define QOSCONTROL5_OFFSET	0x80
#define QOSCONFIG4_OFFSET	0x84
#define QOSCONTROL5_OFFSET	0x88
#define QOSCONFIG5_OFFSET	0x8c
#define QOSCONTROL6_OFFSET	0x90
#define QOSCONFIG6_OFFSET	0x94
#define QOSCONTROL7_OFFSET	0x98
#define QOSCONFIG7_OFFSET	0x9c

#define S5P_CONCONTROL		S5P_DMC_BASE(CONCONTROL_OFFSET)
#define S5P_MEMCONTROL		S5P_DMC_BASE(MEMCONTROL_OFFSET)
#define S5P_MEMCONFIG0		S5P_DMC_BASE(MEMCONFIG0_OFFSET)
#define S5P_MEMCONFIG1		S5P_DMC_BASE(MEMCONFIG1_OFFSET)
#define S5P_DIRECTCMD		S5P_DMC_BASE(DIRECTCMD_OFFSET)
#define S5P_PRECHCONFIG		S5P_DMC_BASE(PRECHCONFIG_OFFSET)
#define S5P_PHYCONTROL0		S5P_DMC_BASE(PHYCONTROL0_OFFSET)
#define S5P_PHYCONTROL1		S5P_DMC_BASE(PHYCONTROL1_OFFSET)
#define S5P_PHYCONTROL2		S5P_DMC_BASE(PHYCONTROL2_OFFSET)
#define S5P_PWRDNCONFIG		S5P_DMC_BASE(PWRDNCONFIG_OFFSET)
#define S5P_TIMINGAREF		S5P_DMC_BASE(TIMINGAREF_OFFSET)
#define S5P_TIMINGROW		S5P_DMC_BASE(TIMINGROW_OFFSET)
#define S5P_TIMINGDATA		S5P_DMC_BASE(TIMINGDATA_OFFSET)
#define S5P_TIMINGPOWER		S5P_DMC_BASE(TIMINGPOWER_OFFSET)
#define S5P_PHYSTATUS0		S5P_DMC_BASE(PHYSTATUS0_OFFSET)
#define S5P_PHYSTATUS1		S5P_DMC_BASE(PHYSTATUS1_OFFSET)
#define S5P_CHIP0STATUS		S5P_DMC_BASE(CHIP0STATUS_OFFSET)
#define S5P_CHIP1STATUS		S5P_DMC_BASE(CHIP1STATUS_OFFSET)
#define S5P_AREFSTATUS		S5P_DMC_BASE(AREFSTATUS_OFFSET)
#define S5P_MRSTATUS		S5P_DMC_BASE(MRSTATUS_OFFSET)
#define S5P_PHYTEST0		S5P_DMC_BASE(PHYTEST0_OFFSET)
#define S5P_PHYTEST1		S5P_DMC_BASE(PHYTEST1_OFFSET)

#define S5P_QOSCONTROL0		S5P_DMC_BASE(QOSCONTROL0_OFFSET)
#define S5P_QOSCONFIG0		S5P_DMC_BASE(QOSCONFIG0_OFFSET)
#define S5P_QOSCONTROL1		S5P_DMC_BASE(QOSCONTROL1_OFFSET)
#define S5P_QOSCONFIG1		S5P_DMC_BASE(QOSCONFIG1_OFFSET)
#define S5P_QOSCONTROL2		S5P_DMC_BASE(QOSCONTROL2_OFFSET)
#define S5P_QOSCONFIG2		S5P_DMC_BASE(QOSCONFIG2_OFFSET)
#define S5P_QOSCONTROL3		S5P_DMC_BASE(QOSCONTROL3_OFFSET)
#define S5P_QOSCONFIG3		S5P_DMC_BASE(QOSCONFIG3_OFFSET)
#define S5P_QOSCONTROL4		S5P_DMC_BASE(QOSCONTROL4_OFFSET)
#define S5P_QOSCONFIG4		S5P_DMC_BASE(QOSCONFIG4_OFFSET)
#define S5P_QOSCONTROL5		S5P_DMC_BASE(QOSCONTROL5_OFFSET)
#define S5P_QOSCONFIG5		S5P_DMC_BASE(QOSCONFIG5_OFFSET)
#define S5P_QOSCONTROL6		S5P_DMC_BASE(QOSCONTROL6_OFFSET)
#define S5P_QOSCONFIG6		S5P_DMC_BASE(QOSCONFIG6_OFFSET)
#define S5P_QOSCONTROL7		S5P_DMC_BASE(QOSCONTROL7_OFFSET)
#define S5P_QOSCONFIG7		S5P_DMC_BASE(QOSCONFIG7_OFFSET)


/* SROM */
#define S5P_SROMC_BASE(x)	(S5P_PA_SROMC + (x))

#define SROM_BW_OFFSET		0x0
#define SROM_BC0_OFFSET		0x04
#define SROM_BC1_OFFSET		0x08
#define SROM_BC2_OFFSET		0x0c
#define SROM_BC3_OFFSET		0x10
#define SROM_BC4_OFFSET		0x14
#define SROM_BC5_OFFSET		0x18

#define S5P_SROM_BW			S5P_SROMC_BASE(SROM_BW_OFFSET)
#define S5P_SROM_BC0		S5P_SROMC_BASE(SROM_BC0_OFFSET)
#define S5P_SROM_BC1		S5P_SROMC_BASE(SROM_BC1_OFFSET)
#define S5P_SROM_BC2		S5P_SROMC_BASE(SROM_BC2_OFFSET)
#define S5P_SROM_BC3		S5P_SROMC_BASE(SROM_BC3_OFFSET)
#define S5P_SROM_BC4		S5P_SROMC_BASE(SROM_BC4_OFFSET)
#define S5P_SROM_BC5		S5P_SROMC_BASE(SROM_BC5_OFFSET)


/* OneNand */
#define S5P_ONENANDC_BASE(x)	(S5P_PA_ONENANDC + (x))

#define MEM_CFG_OFFSET			0x0
#define BURST_LEN_OFFSET		0x10
#define MEM_RESET_OFFSET		0x20
#define INT_ERR_STAT_OFFSET		0x30
#define INT_ERR_MASK_OFFSET		0x40
#define INT_ERR_ACK_OFFSET		0x50
#define ECC_ERR_STAT_1_OFFSET	0x60
#define MANUFACT_ID_OFFSET		0x70
#define DEVICE_ID_OFFSET		0x80
#define DATA_BUF_SIZE_OFFSET	0x90
#define BOOT_BUF_SIZE_OFFSET	0xa0
#define BUF_AMOUNT_OFFSET		0xb0
#define TECH_OFFSET				0xc0
#define FBA_WIDTH_OFFSET		0xd0
#define FPA_WIDTH_OFFSET		0xe0
#define FSA_WIDTH_OFFSET		0xf0
#define REVISION_OFFSET			0x100
#define SYNC_MODE_OFFSET		0x130
#define TRANS_SPARE_OFFSET		0x140
#define PAGE_CNT_OFFSET			0x170
#define ERR_PAGE_ADDR_OFFSET	0x180
#define BURST_RD_LAT_OFFSET		0x190
#define INT_PIN_ENABLE_OFFSET	0x1a0
#define INT_MON_CYC_OFFSET		0x1b0
#define ACC_CLOCK_OFFSET		0x1c0
#define ERR_BLK_ADDR_OFFSET		0x1e0
#define FLASH_VER_ID_OFFSET		0x1f0
#define BANK_EN_OFFSET			0x220
#define WTCHDG_RST_L_OFFSET		0x260
#define WTCHDG_RST_H_OFFSET		0x270
#define SYNC_WRITE_OFFSET		0x280
#define CACHE_READ_OFFSET		0x290
#define COLD_RST_DLY_OFFSET		0x2a0
#define DDP_DEVICE_OFFSET		0x2b0
#define MULTI_PLANE_OFFSET		0x2c0
#define TRANS_MODE_OFFSET		0x2e0
#define DEV_STAT_OFFSET			0x2f0
#define ECC_ERR_STAT_2_OFFSET	0x300
#define ECC_ERR_STAT_3_OFFSET	0x310
#define ECC_ERR_STAT_4_OFFSET	0x320
#define EFCT_BUF_CNT_OFFSET		0x330
#define DEV_PAGE_SIZE_OFFSET	0x340
#define SUPERLOAD_EN_OFFSET		0x350
#define CACHE_PRG_EN_OFFSET		0x360
#define SINGLE_PAGE_BUF_OFFSET	0x370
#define OFFSET_ADDR_OFFSET		0x380
#define INT_MON_STATUS_OFFSET	0x390

#define S5P_MEM_CFG			S5P_ONENANDC_BASE(MEM_CFG_OFFSET)
#define S5P_BURST_LEN		S5P_ONENANDC_BASE(BURST_LEN_OFFSET)
#define S5P_MEM_RESET		S5P_ONENANDC_BASE(MEM_RESET_OFFSET)
#define S5P_INT_ERR_STAT	S5P_ONENANDC_BASE(INT_ERR_STAT_OFFSET)
#define S5P_INT_ERR_MASK	S5P_ONENANDC_BASE(INT_ERR_MASK_OFFSET)
#define S5P_INT_ERR_ACK		S5P_ONENANDC_BASE(INT_ERR_ACK_OFFSET)
#define S5P_ECC_ERR_STAT_1	S5P_ONENANDC_BASE(ECC_ERR_STAT_1_OFFSET)
#define S5P_MANUFACT_ID		S5P_ONENANDC_BASE(MANUFACT_ID_OFFSET)
#define S5P_DEVICE_ID		S5P_ONENANDC_BASE(DEVICE_ID_OFFSET)
#define S5P_DATA_BUF_SIZE	S5P_ONENANDC_BASE(DATA_BUF_SIZE_OFFSET)
#define S5P_BOOT_BUF_SIZE	S5P_ONENANDC_BASE(BOOT_BUF_SIZE_OFFSET)
#define S5P_BUF_AMOUNT		S5P_ONENANDC_BASE(BUF_AMOUNT_OFFSET)
#define S5P_TECH			S5P_ONENANDC_BASE(TECH_OFFSET)
#define S5P_FBA_WIDTH		S5P_ONENANDC_BASE(FBA_WIDTH_OFFSET)
#define S5P_FPA_WIDTH		S5P_ONENANDC_BASE(FPA_WIDTH_OFFSET)
#define S5P_FSA_WIDTH		S5P_ONENANDC_BASE(FSA_WIDTH_OFFSET)
#define S5P_REVISION		S5P_ONENANDC_BASE(REVISION_OFFSET)
#define S5P_SYNC_MODE		S5P_ONENANDC_BASE(SYNC_MODE_OFFSET)
#define S5P_TRANS_SPARE		S5P_ONENANDC_BASE(TRANS_SPARE_OFFSET)
#define S5P_PAGE_CNT		S5P_ONENANDC_BASE(PAGE_CNT_OFFSET)
#define S5P_ERR_PAGE_ADDR	S5P_ONENANDC_BASE(ERR_PAGE_ADDR_OFFSET)
#define S5P_BURST_RD_LAT	S5P_ONENANDC_BASE(BURST_RD_LAT_OFFSET)
#define S5P_INT_PIN_ENABLE	S5P_ONENANDC_BASE(INT_PIN_ENABLE_OFFSET)
#define S5P_INT_MON_CYC		S5P_ONENANDC_BASE(INT_MON_CYC_OFFSET)
#define S5P_ACC_CLOCK		S5P_ONENANDC_BASE(ACC_CLOCK_OFFSET)
#define S5P_ERR_BLK_ADDR	S5P_ONENANDC_BASE(ERR_BLK_ADDR_OFFSET)
#define S5P_FLASH_VER_ID	S5P_ONENANDC_BASE(FLASH_VER_ID_OFFSET)
#define S5P_BANK_EN			S5P_ONENANDC_BASE(BANK_EN_OFFSET)
#define S5P_WTCHDG_RST_L	S5P_ONENANDC_BASE(WTCHDG_RST_L_OFFSET)
#define S5P_WTCHDG_RST_H	S5P_ONENANDC_BASE(WTCHDG_RST_H_OFFSET)
#define S5P_SYNC_WRITE		S5P_ONENANDC_BASE(SYNC_WRITE_OFFSET)
#define S5P_CACHE_READ		S5P_ONENANDC_BASE(CACHE_READ_OFFSET)
#define S5P_COLD_RST_DLY	S5P_ONENANDC_BASE(COLD_RST_DLY_OFFSET)
#define S5P_DDP_DEVICE		S5P_ONENANDC_BASE(DDP_DEVICE_OFFSET)
#define S5P_MULTI_PLANE		S5P_ONENANDC_BASE(MULTI_PLANE_OFFSET)
#define S5P_MEM_CNT			S5P_ONENANDC_BASE(MEM_CNT_OFFSET)
#define S5P_TRANS_MODE		S5P_ONENANDC_BASE(TRANS_MODE_OFFSET)
#define S5P_DEV_START		S5P_ONENANDC_BASE(DEV_START_OFFSET)
#define S5P_ECC_ERR_STAT_2	S5P_ONENANDC_BASE(ECC_ERR_STAT_2_OFFSET)
#define S5P_ECC_ERR_STAT_3	S5P_ONENANDC_BASE(ECC_ERR_STAT_3_OFFSET)
#define S5P_ECC_ERR_STAT_4	S5P_ONENANDC_BASE(ECC_ERR_STAT_4_OFFSET)
#define S5P_EFCT_BUF_CNT	S5P_ONENANDC_BASE(EFCT_BUF_CNT_OFFSET)
#define S5P_DEV_PAGE_SIZE	S5P_ONENANDC_BASE(DEV_PAGE_SIZE_OFFSET)
#define S5P_SUPERLOAD_EN	S5P_ONENANDC_BASE(SUPERLOAD_EN_OFFSET)
#define S5P_CACHE_PRG_EN	S5P_ONENANDC_BASE(CACHE_PRG_EN_OFFSET)
#define S5P_SINGLE_PAGE_BUF	S5P_ONENANDC_BASE(SINGLE_PAGE_BUF_OFFSET)
#define S5P_OFFSET_ADDR		S5P_ONENANDC_BASE(OFFSET_ADDR_OFFSET)
#define S5P_INT_MON_STATUS	S5P_ONENANDC_BASE(INT_MON_STATUS_OFFSET)




/*
 * Timer 
 * : PWM, Watchdog, System timer, RTC
 */

/* PWM */
#define S5P_PWMTIMER_BASE(x)	(S5P_PA_PWMTIMER + (x))

#define TCFG0_OFFSET		0x0
#define TCFG1_OFFSET		0x04
#define TCON_OFFSET			0x08
#define TCNTB0_OFFSET		0x0c
#define TCMPB0_OFFSET		0x10
#define TCNTO0_OFFSET		0x14
#define TCNTB1_OFFSET		0x18
#define TCMPB1_OFFSET		0x1c
#define TCNTO1_OFFSET		0x20
#define TCNTB2_OFFSET		0x24
#define TCMPB2_OFFSET		0x28
#define TCNTO2_OFFSET		0x2c
#define TCNTB3_OFFSET		0x30
#define TCNTO3_OFFSET		0x38
#define TCNTB4_OFFSET		0x3c
#define TCNTO4_OFFSET		0x40
#define TINT_CSTAT_OFFSET	0x44

#define S5P_TCFG0		S5P_PWMTIMER_BASE(TCFG0_OFFSET)
#define S5P_TCFG1		S5P_PWMTIMER_BASE(TCFG1_OFFSET)
#define S5P_TCON		S5P_PWMTIMER_BASE(TCON_OFFSET)
#define S5P_TCNTB0		S5P_PWMTIMER_BASE(TCNTB0_OFFSET)
#define S5P_TCMPB0		S5P_PWMTIMER_BASE(TCMPB0_OFFSET)
#define S5P_TCNTO0		S5P_PWMTIMER_BASE(TCNTO0_OFFSET)
#define S5P_TCNTB1		S5P_PWMTIMER_BASE(TCNTB1_OFFSET)
#define S5P_TCMPB1		S5P_PWMTIMER_BASE(TCMPB1_OFFSET)
#define S5P_TCNTO1		S5P_PWMTIMER_BASE(TCNTO1_OFFSET)
#define S5P_TCNTB2		S5P_PWMTIMER_BASE(TCNTB2_OFFSET)
#define S5P_TCMPB2		S5P_PWMTIMER_BASE(TCMPB2_OFFSET)
#define S5P_TCNTO2		S5P_PWMTIMER_BASE(TCNTO2_OFFSET)
#define S5P_TCNTB3		S5P_PWMTIMER_BASE(TCNTB3_OFFSET)
#define S5P_TCNTO3		S5P_PWMTIMER_BASE(TCNTO3_OFFSET)
#define S5P_TCNTB4		S5P_PWMTIMER_BASE(TCNTB4_OFFSET)
#define S5P_TCNTO4		S5P_PWMTIMER_BASE(TCNTO4_OFFSET)
#define S5P_TINT_CSTAT	S5P_PWMTIMER_BASE(TINT_CSTAT_OFFSET)


/* System Timer */
#define S5P_SYSTIMER_BASE(x)	(S5P_PA_SYSTEM + (x))

#define TCFG_OFFSET			0x0
#define TCON_OFFSET			0x04
#define TCNTB_OFFSET		0x08
#define TCNTO_OFFSET		0x0c
#define ICNTB_OFFSET		0x10
#define ICNTO_OFFSET		0x14
#define INT_CSTAT_OFFSET	0x18

#define S5P_TCFG		S5P_SYSTIMER_BASE(TCFG_OFFSET)
#define S5P_TCON		S5P_SYSTIMER_BASE(TCON_OFFSET)
#define S5P_TCNTB		S5P_SYSTIMER_BASE(TCNTB_OFFSET)
#define S5P_TCNTO		S5P_SYSTIMER_BASE(TCNTO_OFFSET)
#define S5P_ICNTB		S5P_SYSTIMER_BASE(ICNTB_OFFSET)
#define S5P_ICNTO		S5P_SYSTIMER_BASE(ICNTO_OFFSET)
#define S5P_INT_CSTAT	S5P_SYSTIMER_BASE(INT_CSTAT_OFFSET)


/* Watchdog */
#define S5P_WATCHDOG_BASE(x)	(S5P_PA_WATCHDOG + (x))


/* RTC */
#define S5P_RTC_BASE(x)			(S5P_PA_RTC + (x))



/* 
 * UART
 */
#define S5P_PA_UART		S5P_ADDR(0x0c000000)    /* UART */


#endif /*__S5PC100_H__*/




