#ifndef __S5PC1XX_ONENAND_H__
#define __S5PC1XX_ONENAND_H__

#include <asm/hardware.h>

/*
 * OneNAND Controller
 */
#define S5P_ONENAND_BASE	0xE7100000

#define MEM_CFG0_OFFSET		0x0000
#define BURST_LEN0_OFFSET	0x0010
#define MEM_RESET0_OFFSET	0x0020
#define INT_ERR_STAT0_OFFSET	0x0030
#define INT_ERR_MASK0_OFFSET	0x0040
#define INT_ERR_ACK0_OFFSET	0x0050
#define ECC_ERR_STAT0_OFFSET	0x0060
#define MANUFACT_ID0_OFFSET	0x0070
#define DEVICE_ID0_OFFSET	0x0080
#define DATA_BUF_SIZE0_OFFSET	0x0090
#define BOOT_BUF_SIZE0_OFFSET	0x00A0
#define BUF_AMOUNT0_OFFSET	0x00B0
#define TECH0_OFFSET		0x00C0
#define FBA_WIDTH0_OFFSET	0x00D0
#define FPA_WIDTH0_OFFSET	0x00E0
#define FSA_WIDTH0_OFFSET	0x00F0
#define TRANS_SPARE0_OFFSET	0x0140
#define DBS_DFS_WIDTH0_OFFSET	0x0160
#define INT_PIN_ENABLE0_OFFSET	0x01A0
#define ACC_CLOCK0_OFFSET	0x01C0
#define FLASH_VER_ID0_OFFSET	0x01F0
#define FLASH_AUX_CNTRL0_OFFSET	0x0300

#define MEM_CFG0_REG		__REG(S5P_ONENAND_BASE + MEM_CFG0_OFFSET)
#define BURST_LEN0_REG		__REG(S5P_ONENAND_BASE + BURST_LEN0_OFFSET)
#define MEM_RESET0_REG		__REG(S5P_ONENAND_BASE + MEM_RESET0_OFFSET)
#define INT_ERR_STAT0_REG	__REG(S5P_ONENAND_BASE + INT_ERR_STAT0_OFFSET)
#define INT_ERR_MASK0_REG	__REG(S5P_ONENAND_BASE + INT_ERR_MASK0_OFFSET)
#define INT_ERR_ACK0_REG	__REG(S5P_ONENAND_BASE + INT_ERR_ACK0_OFFSET)
#define ECC_ERR_STAT0_REG	__REG(S5P_ONENAND_BASE + ECC_ERR_STAT0_OFFSET)
#define MANUFACT_ID0_REG	__REG(S5P_ONENAND_BASE + MANUFACT_ID0_OFFSET)
#define DEVICE_ID0_REG		__REG(S5P_ONENAND_BASE + DEVICE_ID0_OFFSET)
#define DATA_BUF_SIZE0_REG	__REG(S5P_ONENAND_BASE + DATA_BUF_SIZE0_OFFSET)
#define FBA_WIDTH0_REG		__REG(S5P_ONENAND_BASE + FBA_WIDTH0_OFFSET)
#define FPA_WIDTH0_REG		__REG(S5P_ONENAND_BASE + FPA_WIDTH0_OFFSET)
#define FSA_WIDTH0_REG		__REG(S5P_ONENAND_BASE + FSA_WIDTH0_OFFSET)
#define TRANS_SPARE0_REG	__REG(S5P_ONENAND_BASE + TRANS_SPARE0_OFFSET)
#define DBS_DFS_WIDTH0_REG	__REG(S5P_ONENAND_BASE + DBS_DFS_WIDTH0_OFFSET)
#define INT_PIN_ENABLE0_REG	__REG(S5P_ONENAND_BASE + INT_PIN_ENABLE0_OFFSET)
#define ACC_CLOCK0_REG		__REG(S5P_ONENAND_BASE + ACC_CLOCK0_OFFSET)
#define FLASH_VER_ID0_REG	__REG(S5P_ONENAND_BASE + FLASH_VER_ID0_OFFSET)
#define FLASH_AUX_CNTRL0_REG	__REG(S5P_ONENAND_BASE + FLASH_AUX_CNTRL0_OFFSET)

#define ONENAND_MEM_RESET_HOT	0x3
#define ONENAND_MEM_RESET_COLD	0x2
#define ONENAND_MEM_RESET_WARM	0x1

#define CACHE_OP_ERR    (1 << 13)
#define RST_CMP         (1 << 12)
#define RDY_ACT         (1 << 11)
#define INT_ACT         (1 << 10)
#define UNSUP_CMD       (1 << 9)
#define LOCKED_BLK      (1 << 8)
#define BLK_RW_CMP      (1 << 7)
#define ERS_CMP         (1 << 6)
#define PGM_CMP         (1 << 5)
#define LOAD_CMP        (1 << 4)
#define ERS_FAIL        (1 << 3)
#define PGM_FAIL        (1 << 2)
#define INT_TO          (1 << 1)
#define LD_FAIL_ECC_ERR (1 << 0)

#define TSRF		(1 << 0)

#endif
